import { LanguageProps } from "../../types and interfaces/loaderTypes";

export const titles = [
  {
    code: "Custom",
    id: "custom",
  },
  {
    code: "Bug",
    id: "bug",
  },
  {
    code: "Feature",
    id: "feature",
  },
  {
    code: "Documentation",
    id: "documentation",
  },
  {
    code: "Design",
    id: "design",
  },
  {
    code: "Translation",
    id: "translation",
  },
  {
    code: "Question",
    id: "question",
  },
  {
    code: "Content",
    id: "content",
  },
  {
    code: "Accessibility",
    id: "accessibility",
  },
  {
    code: "Performance",
    id: "performance",
  },
  {
    code: "Security",
    id: "security",
  },
  {
    code: "Community",
    id: "community",
  },
  {
    code: "Feedback",
    id: "feedback",
  },
];

export const systemLanguages: LanguageProps[] = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengali" },
  { code: "pa", name: "Punjabi" },
  { code: "tr", name: "Turkish" },
  { code: "nl", name: "Dutch" },
  { code: "sv", name: "Swedish" },
  { code: "fi", name: "Finnish" },
  { code: "da", name: "Danish" },
  { code: "no", name: "Norwegian" },
  { code: "pl", name: "Polish" },
  { code: "uk", name: "Ukrainian" },
  { code: "cs", name: "Czech" },
  { code: "el", name: "Greek" },
  { code: "hu", name: "Hungarian" },
  { code: "ro", name: "Romanian" },
  { code: "th", name: "Thai" },
  { code: "vi", name: "Vietnamese" },
  { code: "id", name: "Indonesian" },
  { code: "ms", name: "Malay" },
  { code: "he", name: "Hebrew" },
  { code: "fa", name: "Persian" },
  { code: "ur", name: "Urdu" },
  { code: "tl", name: "Filipino" },
  { code: "af", name: "Afrikaans" },
  { code: "sw", name: "Swahili" },
  { code: "zu", name: "Zulu" },
  { code: "xh", name: "Xhosa" },
  { code: "ny", name: "Chichewa" },
  { code: "st", name: "Sesotho" },
  { code: "sn", name: "Shona" },
  { code: "am", name: "Amharic" },
  { code: "ha", name: "Hausa" },
  { code: "yo", name: "Yoruba" },
  { code: "ig", name: "Igbo" },
  { code: "mg", name: "Malagasy" },
  { code: "ne", name: "Nepali" },
  { code: "si", name: "Sinhala" },
  { code: "km", name: "Khmer" },
  { code: "lo", name: "Lao" },
  { code: "my", name: "Burmese" },
  { code: "ka", name: "Georgian" },
  { code: "hy", name: "Armenian" },
  { code: "az", name: "Azerbaijani" },
  { code: "kk", name: "Kazakh" },
  { code: "uz", name: "Uzbek" },
  { code: "ky", name: "Kyrgyz" },
  { code: "tg", name: "Tajik" },
  { code: "mn", name: "Mongolian" },
  { code: "ps", name: "Pashto" },
  { code: "ku", name: "Kurdish" },
  { code: "sd", name: "Sindhi" },
  { code: "bo", name: "Tibetan" },
  { code: "dv", name: "Dhivehi" },
  { code: "tk", name: "Turkmen" },
  { code: "tt", name: "Tatar" },
  { code: "cv", name: "Chuvash" },
  { code: "jv", name: "Javanese" },
  { code: "su", name: "Sundanese" },
  { code: "ceb", name: "Cebuano" },
  { code: "hmn", name: "Hmong" },
  { code: "haw", name: "Hawaiian" },
  { code: "mi", name: "Maori" },
  { code: "sm", name: "Samoan" },
  { code: "to", name: "Tongan" },
  { code: "fj", name: "Fijian" },
  { code: "gu", name: "Gujarati" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "kn", name: "Kannada" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "sa", name: "Sanskrit" },
  { code: "as", name: "Assamese" },
  { code: "or", name: "Odia" },
  { code: "mai", name: "Maithili" },
  { code: "gom", name: "Konkani" },
  { code: "doi", name: "Dogri" },
  { code: "sat", name: "Santali" },
  { code: "ks", name: "Kashmiri" },
  { code: "mni", name: "Manipuri" },
  { code: "lus", name: "Mizo" },
  { code: "brx", name: "Bodo" },
  { code: "nia", name: "Nias" },
  { code: "ban", name: "Balinese" },
  { code: "bug", name: "Buginese" },
  { code: "mad", name: "Madurese" },
  { code: "ace", name: "Acehnese" },
  { code: "bjn", name: "Banjar" },
  { code: "min", name: "Minangkabau" },
  { code: "gor", name: "Gorontalo" },
  { code: "pag", name: "Pangasinan" },
  { code: "ilo", name: "Ilocano" },
  { code: "war", name: "Waray" },
  { code: "bik", name: "Bikol" },
  { code: "pam", name: "Kapampangan" },
  { code: "cbk", name: "Chavacano" },
  { code: "tsg", name: "Tausug" },
  { code: "krj", name: "Kinaray-a" },
  { code: "hnn", name: "Hanunoo" },
  { code: "bbc", name: "Batak Toba" },
  { code: "lb", name: "Luxembourgish" },
  { code: "gd", name: "Scottish Gaelic" },
  { code: "ga", name: "Irish" },
  { code: "cy", name: "Welsh" },
  { code: "br", name: "Breton" },
  { code: "kw", name: "Cornish" },
  { code: "gv", name: "Manx" },
  { code: "is", name: "Icelandic" },
  { code: "fo", name: "Faroese" },
  { code: "kl", name: "Greenlandic" },
  { code: "se", name: "Northern Sami" },
  { code: "yi", name: "Yiddish" },
  { code: "sco", name: "Scots" },
  { code: "ang", name: "Old English" },
  { code: "frm", name: "Middle French" },
  { code: "goh", name: "Old High German" },
  { code: "non", name: "Old Norse" },
  { code: "cu", name: "Church Slavic" },
  { code: "got", name: "Gothic" },
  { code: "egy", name: "Ancient Egyptian" },
  { code: "akk", name: "Akkadian" },
  { code: "arc", name: "Aramaic" },
  { code: "cop", name: "Coptic" },
  { code: "phn", name: "Phoenician" },
  { code: "sga", name: "Old Irish" },
  { code: "syc", name: "Classical Syriac" },
  { code: "ave", name: "Avestan" },
  { code: "peo", name: "Old Persian" },
  { code: "pal", name: "Pahlavi" },
  { code: "xpr", name: "Parthian" },
  { code: "sog", name: "Sogdian" },
  { code: "chu", name: "Old Church Slavonic" },
  { code: "pro", name: "Old Provençal" },
  { code: "osp", name: "Old Spanish" },
  { code: "odt", name: "Old Dutch" },
  { code: "grc", name: "Ancient Greek" },
  { code: "lat", name: "Latin" },
  { code: "san", name: "Sanskrit" },
  { code: "pli", name: "Pali" },
  { code: "pra", name: "Prakrit" },
  { code: "inc", name: "Indic" },
  { code: "ira", name: "Iranian" },
  { code: "cel", name: "Celtic" },
  { code: "gem", name: "Germanic" },
  { code: "ine", name: "Indo-European" },
  { code: "sem", name: "Semitic" },
  { code: "afa", name: "Afro-Asiatic" },
  { code: "tut", name: "Altaic" },
  { code: "nai", name: "North American Indian" },
  { code: "sio", name: "Siouan" },
  { code: "alg", name: "Algonquian" },
  { code: "iro", name: "Iroquoian" },
  { code: "cau", name: "Caucasian" },
  { code: "ath", name: "Athapascan" },
  { code: "apa", name: "Apache" },
  { code: "azc", name: "Uto-Aztecan" },
  { code: "myn", name: "Mayan" },
  { code: "oto", name: "Otomian" },
  { code: "omq", name: "Oto-Manguean" },
  { code: "omv", name: "Omotic" },
  { code: "nic", name: "Niger-Kordofanian" },
  { code: "alv", name: "Atlantic-Congo" },
  { code: "bnt", name: "Bantu" },
  { code: "csu", name: "Central Sudanic" },
  { code: "cdc", name: "Chadic" },
  { code: "ber", name: "Berber" },
  { code: "cus", name: "Cushitic" },
  { code: "ssa", name: "Nilo-Saharan" },
  { code: "kho", name: "Khoisan" },
  { code: "aav", name: "Austro-Asiatic" },
  { code: "mkh", name: "Mon-Khmer" },
  { code: "hmx", name: "Hmong-Mien" },
  { code: "tai", name: "Tai-Kadai" },
  { code: "map", name: "Austronesian" },
  { code: "poz", name: "Malayo-Polynesian" },
  { code: "pqe", name: "Eastern Malayo-Polynesian" },
  { code: "phi", name: "Philippine" },
  { code: "btk", name: "Batak" },
  { code: "msa", name: "Malayic" },
  { code: "day", name: "Land Dayak" },
  { code: "btd", name: "Bolaang Mongondow" },
  { code: "srb", name: "Sara Bakati’" },
  { code: "iba", name: "Iban" },
  { code: "kxd", name: "Brunei" },
  { code: "mqy", name: "Manggarai" },
  { code: "sas", name: "Sasak" },
  { code: "snd", name: "Sundanese" },
  { code: "mad", name: "Madurese" },
  { code: "jav", name: "Javanese" },
  { code: "ban", name: "Balinese" },
  { code: "sun", name: "Sundanese" },
  { code: "ace", name: "Acehnese" },
  { code: "bug", name: "Buginese" },
  { code: "min", name: "Minangkabau" },
  { code: "gor", name: "Gorontalo" },
  { code: "mak", name: "Makassarese" },
  { code: "bjn", name: "Banjar" },
  { code: "bbc", name: "Batak Toba" },
  { code: "kvr", name: "Kerinci" },
  { code: "mui", name: "Musi" },
  { code: "rej", name: "Rejang" },
  { code: "lce", name: "Loncong" },
  { code: "lcf", name: "Lubu" },
  { code: "liw", name: "Col" },
  { code: "mfb", name: "Bangka" },
  { code: "mfp", name: "Makassar Malay" },
  { code: "mqg", name: "Kota Bangun Kutai Malay" },
  { code: "msh", name: "Masela" },
  { code: "mui", name: "Musi" },
  { code: "orn", name: "Orang Kanaq" },
  { code: "ors", name: "Orang Seletar" },
  { code: "pel", name: "Pekal" },
  { code: "pse", name: "Central Malay" },
  { code: "tmw", name: "Temuan" },
  { code: "urk", name: "Urak Lawoi" },
  { code: "vkk", name: "Kaur" },
  { code: "vkt", name: "Tenggarong Kutai Malay" },
  { code: "xdy", name: "Malayic Dayak" },
  { code: "abs", name: "Ambonese Malay" },
  { code: "mbf", name: "Baba Malay" },
  { code: "jax", name: "Jambi Malay" },
  { code: "meo", name: "Kedah Malay" },
  { code: "kvb", name: "Kubu" },
  { code: "kvr", name: "Kerinci" },
  { code: "lce", name: "Loncong" },
  { code: "lcf", name: "Lubu" },
  { code: "max", name: "North Moluccan Malay" },
  { code: "mfa", name: "Pattani Malay" },
  { code: "mfp", name: "Makassar Malay" },
  { code: "min", name: "Minangkabau" },
  { code: "mui", name: "Musi" },
  { code: "orn", name: "Orang Kanaq" },
  { code: "ors", name: "Orang Seletar" },
  { code: "pel", name: "Pekal" },
  { code: "pse", name: "Central Malay" },
  { code: "tmw", name: "Temuan" },
  { code: "urk", name: "Urak Lawoi" },
  { code: "vkk", name: "Kaur" },
  { code: "vkt", name: "Tenggarong Kutai Malay" },
  { code: "xdy", name: "Malayic Dayak" },
  { code: "zlm", name: "Malay" },
  { code: "zmi", name: "Negeri Sembilan Malay" },
  { code: "zsm", name: "Standard Malay" },
];

export const availabilityOptions = [
  // 1. Availability Status
  {
    id: "available",
    code: "Available for work",
  },
  {
    id: "limited",
    code: "Limited availability",
  },
  {
    id: "not-available",
    code: "Currently unavailable",
  },

  // 2. Work Schedule
  {
    id: "full-time",
    code: "Full-time (40+ hours/week)",
  },
  {
    id: "part-time",
    code: "Part-time (10-30 hours/week)",
  },
  {
    id: "timezone-remote",
    code: "Remote (time zone based)",
  },

  // 3. Job Types
  {
    id: "long-term",
    code: "Open to long-term contracts",
  },
  {
    id: "short-term",
    code: "Open to short-term projects",
  },

  // 4. Special Badges
  {
    id: "ready-to-interview",
    code: "Ready to interview",
  },
  {
    id: "top-rated-plus",
    code: "Top Rated Plus",
  },
];

export const socialMediaPlatforms = [
  { code: "LinkedIn", id: "linkedin" },
  { code: "Twitter/X", id: "twitter" },
  { code: "GitHub", id: "github" },
  { code: "Discord", id: "discord" },
  { code: "Facebook", id: "facebook" },
  { code: "Telegram", id: "telegram" },
];
