import { LanguageProps } from "../../types and interfaces/loaderTypes";

export const titles = [
  {
    code: "Custom",
    id: "custom",
  },
  {
    code: "Bug",
    id: "bug",
  },
  {
    code: "Feature",
    id: "feature",
  },
  {
    code: "Documentation",
    id: "documentation",
  },
  {
    code: "Design",
    id: "design",
  },
  {
    code: "Translation",
    id: "translation",
  },
  {
    code: "Question",
    id: "question",
  },
  {
    code: "Content",
    id: "content",
  },
  {
    code: "Accessibility",
    id: "accessibility",
  },
  {
    code: "Performance",
    id: "performance",
  },
  {
    code: "Security",
    id: "security",
  },
  {
    code: "Community",
    id: "community",
  },
  {
    code: "Feedback",
    id: "feedback",
  },
];

export const systemLanguages: LanguageProps[] = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Chinese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "ar", name: "Arabic" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengali" },
  { code: "pa", name: "Punjabi" },
  { code: "tr", name: "Turkish" },
  { code: "nl", name: "Dutch" },
  { code: "sv", name: "Swedish" },
  { code: "fi", name: "Finnish" },
  { code: "da", name: "Danish" },
  { code: "no", name: "Norwegian" },
  { code: "pl", name: "Polish" },
  { code: "uk", name: "Ukrainian" },
  { code: "cs", name: "Czech" },
  { code: "el", name: "Greek" },
  { code: "hu", name: "Hungarian" },
  { code: "ro", name: "Romanian" },
  { code: "th", name: "Thai" },
  { code: "vi", name: "Vietnamese" },
  { code: "id", name: "Indonesian" },
  { code: "ms", name: "Malay" },
  { code: "he", name: "Hebrew" },
  { code: "fa", name: "Persian" },
  { code: "ur", name: "Urdu" },
  { code: "tl", name: "Filipino" },
  { code: "af", name: "Afrikaans" },
  { code: "sw", name: "Swahili" },
  { code: "zu", name: "Zulu" },
  { code: "xh", name: "Xhosa" },
  { code: "ny", name: "Chichewa" },
  { code: "st", name: "Sesotho" },
  { code: "sn", name: "Shona" },
  { code: "am", name: "Amharic" },
  { code: "ha", name: "Hausa" },
  { code: "yo", name: "Yoruba" },
  { code: "ig", name: "Igbo" },
  { code: "mg", name: "Malagasy" },
  { code: "ne", name: "Nepali" },
  { code: "si", name: "Sinhala" },
  { code: "km", name: "Khmer" },
  { code: "lo", name: "Lao" },
  { code: "my", name: "Burmese" },
  { code: "ka", name: "Georgian" },
  { code: "hy", name: "Armenian" },
  { code: "az", name: "Azerbaijani" },
  { code: "kk", name: "Kazakh" },
  { code: "uz", name: "Uzbek" },
  { code: "ky", name: "Kyrgyz" },
  { code: "tg", name: "Tajik" },
  { code: "mn", name: "Mongolian" },
  { code: "ps", name: "Pashto" },
  { code: "ku", name: "Kurdish" },
  { code: "sd", name: "Sindhi" },
  { code: "bo", name: "Tibetan" },
  { code: "dv", name: "Dhivehi" },
  { code: "tk", name: "Turkmen" },
  { code: "tt", name: "Tatar" },
  { code: "cv", name: "Chuvash" },
  { code: "jv", name: "Javanese" },
  { code: "su", name: "Sundanese" },
  { code: "ceb", name: "Cebuano" },
  { code: "hmn", name: "Hmong" },
  { code: "haw", name: "Hawaiian" },
  { code: "mi", name: "Maori" },
  { code: "sm", name: "Samoan" },
  { code: "to", name: "Tongan" },
  { code: "fj", name: "Fijian" },
  { code: "gu", name: "Gujarati" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "kn", name: "Kannada" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "sa", name: "Sanskrit" },
  { code: "as", name: "Assamese" },
  { code: "or", name: "Odia" },
  { code: "mai", name: "Maithili" },
  { code: "gom", name: "Konkani" },
  { code: "doi", name: "Dogri" },
  { code: "sat", name: "Santali" },
  { code: "ks", name: "Kashmiri" },
  { code: "mni", name: "Manipuri" },
  { code: "lus", name: "Mizo" },
  { code: "brx", name: "Bodo" },
  { code: "nia", name: "Nias" },
  { code: "ban", name: "Balinese" },
  { code: "bug", name: "Buginese" },
  { code: "mad", name: "Madurese" },
  { code: "ace", name: "Acehnese" },
  { code: "bjn", name: "Banjar" },
  { code: "min", name: "Minangkabau" },
  { code: "gor", name: "Gorontalo" },
  { code: "pag", name: "Pangasinan" },
  { code: "ilo", name: "Ilocano" },
  { code: "war", name: "Waray" },
  { code: "bik", name: "Bikol" },
  { code: "pam", name: "Kapampangan" },
  { code: "cbk", name: "Chavacano" },
  { code: "tsg", name: "Tausug" },
  { code: "krj", name: "Kinaray-a" },
  { code: "hnn", name: "Hanunoo" },
  { code: "bbc", name: "Batak Toba" },
  { code: "lb", name: "Luxembourgish" },
  { code: "gd", name: "Scottish Gaelic" },
  { code: "ga", name: "Irish" },
  { code: "cy", name: "Welsh" },
  { code: "br", name: "Breton" },
  { code: "kw", name: "Cornish" },
  { code: "gv", name: "Manx" },
  { code: "is", name: "Icelandic" },
  { code: "fo", name: "Faroese" },
  { code: "kl", name: "Greenlandic" },
  { code: "se", name: "Northern Sami" },
  { code: "yi", name: "Yiddish" },
  { code: "sco", name: "Scots" },
  { code: "ang", name: "Old English" },
  { code: "frm", name: "Middle French" },
  { code: "goh", name: "Old High German" },
  { code: "non", name: "Old Norse" },
  { code: "cu", name: "Church Slavic" },
  { code: "got", name: "Gothic" },
  { code: "egy", name: "Ancient Egyptian" },
  { code: "akk", name: "Akkadian" },
  { code: "arc", name: "Aramaic" },
  { code: "cop", name: "Coptic" },
  { code: "phn", name: "Phoenician" },
  { code: "sga", name: "Old Irish" },
  { code: "syc", name: "Classical Syriac" },
  { code: "ave", name: "Avestan" },
  { code: "peo", name: "Old Persian" },
  { code: "pal", name: "Pahlavi" },
  { code: "xpr", name: "Parthian" },
  { code: "sog", name: "Sogdian" },
  { code: "chu", name: "Old Church Slavonic" },
  { code: "pro", name: "Old Provençal" },
  { code: "osp", name: "Old Spanish" },
  { code: "odt", name: "Old Dutch" },
  { code: "grc", name: "Ancient Greek" },
  { code: "lat", name: "Latin" },
  { code: "san", name: "Sanskrit" },
  { code: "pli", name: "Pali" },
  { code: "pra", name: "Prakrit" },
  { code: "inc", name: "Indic" },
  { code: "ira", name: "Iranian" },
  { code: "cel", name: "Celtic" },
  { code: "gem", name: "Germanic" },
  { code: "ine", name: "Indo-European" },
  { code: "sem", name: "Semitic" },
  { code: "afa", name: "Afro-Asiatic" },
  { code: "tut", name: "Altaic" },
  { code: "nai", name: "North American Indian" },
  { code: "sio", name: "Siouan" },
  { code: "alg", name: "Algonquian" },
  { code: "iro", name: "Iroquoian" },
  { code: "cau", name: "Caucasian" },
  { code: "ath", name: "Athapascan" },
  { code: "apa", name: "Apache" },
  { code: "azc", name: "Uto-Aztecan" },
  { code: "myn", name: "Mayan" },
  { code: "oto", name: "Otomian" },
  { code: "omq", name: "Oto-Manguean" },
  { code: "omv", name: "Omotic" },
  { code: "nic", name: "Niger-Kordofanian" },
  { code: "alv", name: "Atlantic-Congo" },
  { code: "bnt", name: "Bantu" },
  { code: "csu", name: "Central Sudanic" },
  { code: "cdc", name: "Chadic" },
  { code: "ber", name: "Berber" },
  { code: "cus", name: "Cushitic" },
  { code: "ssa", name: "Nilo-Saharan" },
  { code: "kho", name: "Khoisan" },
  { code: "aav", name: "Austro-Asiatic" },
  { code: "mkh", name: "Mon-Khmer" },
  { code: "hmx", name: "Hmong-Mien" },
  { code: "tai", name: "Tai-Kadai" },
  { code: "map", name: "Austronesian" },
  { code: "poz", name: "Malayo-Polynesian" },
  { code: "pqe", name: "Eastern Malayo-Polynesian" },
  { code: "phi", name: "Philippine" },
  { code: "btk", name: "Batak" },
  { code: "msa", name: "Malayic" },
  { code: "day", name: "Land Dayak" },
  { code: "btd", name: "Bolaang Mongondow" },
  { code: "srb", name: "Sara Bakati’" },
  { code: "iba", name: "Iban" },
  { code: "kxd", name: "Brunei" },
  { code: "mqy", name: "Manggarai" },
  { code: "sas", name: "Sasak" },
  { code: "snd", name: "Sundanese" },
  { code: "mad", name: "Madurese" },
  { code: "jav", name: "Javanese" },
  { code: "ban", name: "Balinese" },
  { code: "sun", name: "Sundanese" },
  { code: "ace", name: "Acehnese" },
  { code: "bug", name: "Buginese" },
  { code: "min", name: "Minangkabau" },
  { code: "gor", name: "Gorontalo" },
  { code: "mak", name: "Makassarese" },
  { code: "bjn", name: "Banjar" },
  { code: "bbc", name: "Batak Toba" },
  { code: "kvr", name: "Kerinci" },
  { code: "mui", name: "Musi" },
  { code: "rej", name: "Rejang" },
  { code: "lce", name: "Loncong" },
  { code: "lcf", name: "Lubu" },
  { code: "liw", name: "Col" },
  { code: "mfb", name: "Bangka" },
  { code: "mfp", name: "Makassar Malay" },
  { code: "mqg", name: "Kota Bangun Kutai Malay" },
  { code: "msh", name: "Masela" },
  { code: "mui", name: "Musi" },
  { code: "orn", name: "Orang Kanaq" },
  { code: "ors", name: "Orang Seletar" },
  { code: "pel", name: "Pekal" },
  { code: "pse", name: "Central Malay" },
  { code: "tmw", name: "Temuan" },
  { code: "urk", name: "Urak Lawoi" },
  { code: "vkk", name: "Kaur" },
  { code: "vkt", name: "Tenggarong Kutai Malay" },
  { code: "xdy", name: "Malayic Dayak" },
  { code: "abs", name: "Ambonese Malay" },
  { code: "mbf", name: "Baba Malay" },
  { code: "jax", name: "Jambi Malay" },
  { code: "meo", name: "Kedah Malay" },
  { code: "kvb", name: "Kubu" },
  { code: "kvr", name: "Kerinci" },
  { code: "lce", name: "Loncong" },
  { code: "lcf", name: "Lubu" },
  { code: "max", name: "North Moluccan Malay" },
  { code: "mfa", name: "Pattani Malay" },
  { code: "mfp", name: "Makassar Malay" },
  { code: "min", name: "Minangkabau" },
  { code: "mui", name: "Musi" },
  { code: "orn", name: "Orang Kanaq" },
  { code: "ors", name: "Orang Seletar" },
  { code: "pel", name: "Pekal" },
  { code: "pse", name: "Central Malay" },
  { code: "tmw", name: "Temuan" },
  { code: "urk", name: "Urak Lawoi" },
  { code: "vkk", name: "Kaur" },
  { code: "vkt", name: "Tenggarong Kutai Malay" },
  { code: "xdy", name: "Malayic Dayak" },
  { code: "zlm", name: "Malay" },
  { code: "zmi", name: "Negeri Sembilan Malay" },
  { code: "zsm", name: "Standard Malay" },
];

export const availabilityOptions = [
  // 1. Availability Status
  {
    id: "available",
    code: "Available for work",
  },
  {
    id: "limited",
    code: "Limited availability",
  },
  {
    id: "not-available",
    code: "Currently unavailable",
  },

  // 2. Work Schedule
  {
    id: "full-time",
    code: "Full-time (40+ hours/week)",
  },
  {
    id: "part-time",
    code: "Part-time (10-30 hours/week)",
  },
  {
    id: "timezone-remote",
    code: "Remote (time zone based)",
  },

  // 3. Job Types
  {
    id: "long-term",
    code: "Open to long-term contracts",
  },
  {
    id: "short-term",
    code: "Open to short-term projects",
  },

  // 4. Special Badges
  {
    id: "ready-to-interview",
    code: "Ready to interview",
  },
  {
    id: "top-rated-plus",
    code: "Top Rated Plus",
  },
];

export const urlType = [
  { code: "Link", id: "link" },
  { code: "Handle", id: "handle" },
];

// Import React Icons (install with: npm install react-icons)
import {
  FaLinkedin,
  FaTwitter,
  FaGithub,
  FaDiscord,
  FaFacebook,
  FaTelegram,
  FaInstagram,
  FaYoutube,
  FaTiktok,
  FaWhatsapp,
  FaSnapchat,
  FaPinterest,
  FaReddit,
  FaTwitch,
  FaMedium,
  FaBehance,
  FaDribbble,
  FaStackOverflow,
  FaDev,
  FaSlack,
  FaSkype,
  FaVimeo,
  FaFlickr,
  FaSpotify,
  FaSoundcloud,
  FaPatreon,
  FaAngellist,
  FaProductHunt,
  FaHackerNews,
  FaQuora,
  FaTumblr,
  FaFoursquare,
  FaYelp,
  FaMeetup,
  FaStrava,
  FaUntappd,
  FaImdb,
  FaXing,
  FaVk,
  FaQq,
  FaWeibo,
} from "react-icons/fa";
import { FaXTwitter, FaThreads, FaMastodon, FaBluesky } from "react-icons/fa6";

import {
  SiSignal,
  SiZoom,
  Si500Px,
  SiGoodreads,
  SiBandcamp,
  SiKofi,
  SiOnlyfans,
  SiSubstack,
  SiClubhouse,
  SiWechat,
  SiLine,
  SiViber,
  SiEventbrite,
  SiLetterboxd,
  SiLastdotfm,
  SiIndeed,
  SiOdnoklassniki,
  SiXiaohongshu,
} from "react-icons/si";

export const socialMediaPlatforms = [
  {
    code: "LinkedIn",
    id: "LinkedIn",
    icon: FaLinkedin,
    color: "#0077B5",
    darkColor: "#004182",
  },
  {
    code: "Twitter/X",
    id: "Twitter/X",
    icon: FaXTwitter,
    color: "#000000",
    darkColor: "#1D9BF0",
  },
  {
    code: "GitHub",
    id: "GitHub",
    icon: FaGithub,
    color: "#ffffff",
    darkColor: "#000000",
  },
  {
    code: "Discord",
    id: "Discord",
    icon: FaDiscord,
    color: "#5865F2",
    darkColor: "#404EED",
  },
  {
    code: "Facebook",
    id: "Facebook",
    icon: FaFacebook,
    color: "#1877F2",
    darkColor: "#166FE5",
  },
  {
    code: "Telegram",
    id: "Telegram",
    icon: FaTelegram,
    color: "#26A5E4",
    darkColor: "#229ED9",
  },
  {
    code: "Instagram",
    id: "Instagram",
    icon: FaInstagram,
    color: "#E4405F",
    darkColor: "#C13584",
  },
  {
    code: "YouTube",
    id: "YouTube",
    icon: FaYoutube,
    color: "#FF0000",
    darkColor: "#CC0000",
  },
  {
    code: "TikTok",
    id: "TikTok",
    icon: FaTiktok,
    color: "#000000",
    darkColor: "#FF0050",
  },
  {
    code: "WhatsApp",
    id: "WhatsApp",
    icon: FaWhatsapp,
    color: "#25D366",
    darkColor: "#128C7E",
  },
  {
    code: "Snapchat",
    id: "Snapchat",
    icon: FaSnapchat,
    color: "#FFFC00",
    darkColor: "#FDD835",
  },
  {
    code: "Pinterest",
    id: "Pinterest",
    icon: FaPinterest,
    color: "#BD081C",
    darkColor: "#E60023",
  },
  {
    code: "Reddit",
    id: "Reddit",
    icon: FaReddit,
    color: "#FF4500",
    darkColor: "#FF5722",
  },
  {
    code: "Twitch",
    id: "Twitch",
    icon: FaTwitch,
    color: "#9146FF",
    darkColor: "#772CE8",
  },
  {
    code: "Medium",
    id: "Medium",
    icon: FaMedium,
    color: "#000000",
    darkColor: "#FFFFFF",
  },
  {
    code: "Behance",
    id: "Behance",
    icon: FaBehance,
    color: "#1769FF",
    darkColor: "#0057FF",
  },
  {
    code: "Dribbble",
    id: "Dribbble",
    icon: FaDribbble,
    color: "#EA4C89",
    darkColor: "#E73C7E",
  },
  {
    code: "Stack Overflow",
    id: "Stack Overflow",
    icon: FaStackOverflow,
    color: "#F58025",
    darkColor: "#EF8236",
  },
  {
    code: "Dev.to",
    id: "Dev.to",
    icon: FaDev,
    color: "#0A0A0A",
    darkColor: "#FFFFFF",
  },
  {
    code: "Mastodon",
    id: "Mastodon",
    icon: FaMastodon,
    color: "#563ACC",
    darkColor: "#6364FF",
  },
  {
    code: "Threads",
    id: "Threads",
    icon: FaThreads,
    color: "#000000",
    darkColor: "#FFFFFF",
  },
  {
    code: "Bluesky",
    id: "Bluesky",
    icon: FaBluesky,
    color: "#0085FF",
    darkColor: "#00A8FF",
  },
  {
    code: "Clubhouse",
    id: "Clubhouse",
    icon: SiClubhouse,
    color: "#F2C94C",
    darkColor: "#E6B800",
  },
  {
    code: "Slack",
    id: "Slack",
    icon: FaSlack,
    color: "#4A154B",
    darkColor: "#ECB22E",
  },
  {
    code: "WeChat",
    id: "WeChat",
    icon: SiWechat,
    color: "#07C160",
    darkColor: "#00D100",
  },
  {
    code: "Line",
    id: "Line",
    icon: SiLine,
    color: "#00C300",
    darkColor: "#00B900",
  },
  {
    code: "Viber",
    id: "Viber",
    icon: SiViber,
    color: "#665CAC",
    darkColor: "#7C3AED",
  },
  {
    code: "Signal",
    id: "Signal",
    icon: SiSignal,
    color: "#3A76F0",
    darkColor: "#2563EB",
  },
  {
    code: "Skype",
    id: "Skype",
    icon: FaSkype,
    color: "#00AFF0",
    darkColor: "#0078D4",
  },
  {
    code: "Zoom",
    id: "Zoom",
    icon: SiZoom,
    color: "#2D8CFF",
    darkColor: "#0E71EB",
  },
  {
    code: "Vimeo",
    id: "Vimeo",
    icon: FaVimeo,
    color: "#1AB7EA",
    darkColor: "#00ADEF",
  },
  {
    code: "Flickr",
    id: "Flickr",
    icon: FaFlickr,
    color: "#FF0084",
    darkColor: "#F40083",
  },
  {
    code: "500px",
    id: "500px",
    icon: Si500Px,
    color: "#0099E5",
    darkColor: "#007ACC",
  },
  {
    code: "Goodreads",
    id: "Goodreads",
    icon: SiGoodreads,
    color: "#372213",
    darkColor: "#F4F1EA",
  },
  {
    code: "Spotify",
    id: "Spotify",
    icon: FaSpotify,
    color: "#1ED760",
    darkColor: "#1DB954",
  },
  {
    code: "SoundCloud",
    id: "SoundCloud",
    icon: FaSoundcloud,
    color: "#FF5500",
    darkColor: "#FF7700",
  },
  {
    code: "Bandcamp",
    id: "Bandcamp",
    icon: SiBandcamp,
    color: "#629AA0",
    darkColor: "#1DA0C3",
  },
  {
    code: "Patreon",
    id: "Patreon",
    icon: FaPatreon,
    color: "#FF424D",
    darkColor: "#F96854",
  },
  {
    code: "Ko-fi",
    id: "Ko-fi",
    icon: SiKofi,
    color: "#FF5E5B",
    darkColor: "#13C3FF",
  },
  {
    code: "OnlyFans",
    id: "OnlyFans",
    icon: SiOnlyfans,
    color: "#00AFF0",
    darkColor: "#FFFFFF",
  },
  {
    code: "Substack",
    id: "Substack",
    icon: SiSubstack,
    color: "#FF6719",
    darkColor: "#FF7A00",
  },

  {
    code: "AngelList",
    id: "AngelList",
    icon: FaAngellist,
    color: "#000000",
    darkColor: "#FFFFFF",
  },
  {
    code: "ProductHunt",
    id: "ProductHunt",
    icon: FaProductHunt,
    color: "#DA552F",
    darkColor: "#FF6154",
  },
  {
    code: "Hacker News",
    id: "Hacker News",
    icon: FaHackerNews,
    color: "#FF6600",
    darkColor: "#FF7700",
  },
  {
    code: "Quora",
    id: "Quora",
    icon: FaQuora,
    color: "#B92B27",
    darkColor: "#AA2200",
  },
  {
    code: "Tumblr",
    id: "Tumblr",
    icon: FaTumblr,
    color: "#001935",
    darkColor: "#00CF35",
  },
  {
    code: "Foursquare",
    id: "Foursquare",
    icon: FaFoursquare,
    color: "#F94877",
    darkColor: "#FA4778",
  },
  {
    code: "Yelp",
    id: "Yelp",
    icon: FaYelp,
    color: "#FF1744",
    darkColor: "#D32323",
  },
  {
    code: "Meetup",
    id: "Meetup",
    icon: FaMeetup,
    color: "#ED1C40",
    darkColor: "#F64060",
  },
  {
    code: "Eventbrite",
    id: "Eventbrite",
    icon: SiEventbrite,
    color: "#F05537",
    darkColor: "#FF6633",
  },
  {
    code: "Strava",
    id: "Strava",
    icon: FaStrava,
    color: "#FC4C02",
    darkColor: "#FC5200",
  },
  {
    code: "Untappd",
    id: "Untappd",
    icon: FaUntappd,
    color: "#FFC000",
    darkColor: "#FFB000",
  },
  {
    code: "Letterboxd",
    id: "Letterboxd",
    icon: SiLetterboxd,
    color: "#2C3440",
    darkColor: "#00E054",
  },
  {
    code: "Last.fm",
    id: "Last.fm",
    icon: SiLastdotfm,
    color: "#D51007",
    darkColor: "#BA0000",
  },
  {
    code: "IMDb",
    id: "IMDb",
    icon: FaImdb,
    color: "#F5C518",
    darkColor: "#E6AC00",
  },
  {
    code: "Indeed",
    id: "Indeed",
    icon: SiIndeed,
    color: "#003A9B",
    darkColor: "#2557A7",
  },
  {
    code: "Xing",
    id: "Xing",
    icon: FaXing,
    color: "#026466",
    darkColor: "#1A7B81",
  },
  {
    code: "VKontakte",
    id: "VKontakte",
    icon: FaVk,
    color: "#4C75A3",
    darkColor: "#5181B8",
  },
  {
    code: "Odnoklassniki",
    id: "Odnoklassniki",
    icon: SiOdnoklassniki,
    color: "#EE8208",
    darkColor: "#F5A623",
  },
  {
    code: "QQ",
    id: "QQ",
    icon: FaQq,
    color: "#EB1923",
    darkColor: "#FAAD14",
  },
  {
    code: "Weibo",
    id: "Weibo",
    icon: FaWeibo,
    color: "#DF2029",
    darkColor: "#E6162D",
  },
  {
    code: "Xiaohongshu",
    id: "Xiaohongshu",
    icon: SiXiaohongshu,
    color: "#FF2442",
    darkColor: "#FF1B3B",
  },
];

export const proficiencyLevel = [
  { id: "novice", code: "Novice (0-1 years)" },
  { id: "beginner", code: "Beginner (1-3 years)" },
  { id: "intermediate", code: "Intermediate (3-5 years)" },
  { id: "proficient", code: "Proficient (5-7 years)" },
  { id: "advanced", code: "Advanced (7-10 years)" },
  { id: "master", code: "Master (10+ years)" },
];
