import { LoaderOption } from "../../types and interfaces/loaderTypes";

export const loaderOptions: LoaderOption[] = [
    { id: "spin-loader", code: "Spin Loader" },
    { id: "dots-loader", code: "Dots Loader" },
    { id: "bars-loader", code: "Bars Loader" },
    { id: "wave-loader", code: "Wave Loader" },
    { id: "orbit-loader", code: "Orbit Loader" },
    { id: "grid-loader", code: "Grid Loader" },
    { id: "morph-loader", code: "Morph Loader" },
    { id: "ripple-loader", code: "Ripple Loader" },
    { id: "spiral-loader", code: "Spiral Loader" },
    { id: "cube-flip-loader", code: "Cube Flip Loader" },
    { id: "elastic-loader", code: "Elastic Loader" },
    { id: "gear-loader", code: "Gear Loader" },
    { id: "pendulum-loader", code: "Pendulum Loader" },
    { id: "typing-loader", code: "Typing Loader" },
    { id: "liquid-loader", code: "Liquid Loader" },
    { id: "hexagon-loader", code: "Hexagon Loader" },
    { id: "particle-loader", code: "Particle Loader" },
    { id: "radar-loader", code: "Radar Loader" },
    { id: "infinity-loader", code: "Infinity Loader" },
    { id: "magnetic-loader", code: "Magnetic Loader" },
    { id: "spinner-dots", code: "Spinner Dots" },
    { id: "pulse-ring", code: "Pulse Ring" },
    { id: "zigzag-loader", code: "Zigzag Loader" },
    { id: "bloom-loader", code: "Bloom Loader" },
    { id: "portfolio-pro", code: "Portfolio Pro" },
  ];