// components/projects/projectPromptOptions.ts
import { PromptOption } from "../ai/AIAsistant";

interface ProjectFormData {
  project_name?: string;
  project_category?: string;
  project_summary?: string;
  project_description?: string;
  project_url?: string;
  start_date?: string | null;
  end_date?: string | null;
  client_name?: string;
  budget?: number | null;
  stack?: string[];
  tags?: string[];
}

// Function to generate prompt options for project summary
export const getProjectSummaryPromptOptions = (
  formData: ProjectFormData,
  currentText: string,
): PromptOption[] => {
  const { project_name, project_category } = formData;

  // Return empty array if required fields are missing
  if (!project_name?.trim() || !project_category?.trim()) {
    return [];
  }

  const hasText = currentText.trim().length > 0;
  const name = project_name.trim();
  const category = project_category.trim();
  const stack = formData.stack?.length ? formData.stack.join(", ") : "";
  const tags = formData.tags?.length ? formData.tags.join(", ") : "";
  const client = formData.client_name?.trim();
  const budget = formData.budget;
  const url = formData.project_url?.trim();
  const dateRange = formData.start_date
    ? formData.end_date
      ? `from ${formData.start_date} to ${formData.end_date}`
      : `started ${formData.start_date}`
    : "";

  // Build context-rich description
  const projectContext = [
    category ? `${category} project` : "",
    client ? `for client ${client}` : "",
    budget ? `with a budget of $${budget.toLocaleString()}` : "",
    dateRange ? `(${dateRange})` : "",
  ]
    .filter(Boolean)
    .join(" ");

  const techContext = stack ? ` Built with: ${stack}.` : "";
  const tagContext = tags ? ` Key themes: ${tags}.` : "";
  const urlContext = url ? ` Project URL: ${url}` : "";

  return [
    {
      title: "Improve summary",
      prompt: hasText
        ? `You are a seasoned portfolio consultant and pitch specialist who helps professionals present their work in the most compelling light possible. Rewrite this project summary for "${name}" (${projectContext}) to be dramatically more engaging, polished, and impactful. Your goal is to transform it into a concise yet powerful overview that immediately communicates why this project matters and what makes it impressive. Open with a strong hook that captures the project's essence and value proposition in the first sentence. Clearly articulate the core problem being solved, the target audience or beneficiaries, and the unique approach or innovation that sets this solution apart. Conclude with the key outcome, impact, or value delivered - what changed because this project exists? The summary should make readers (potential employers, clients, collaborators) lean in and think "tell me more about this." Use active, confident language that conveys ownership and pride without sounding boastful.${techContext} Avoid generic phrases like "a project that does X" - instead, show why doing X was important and challenging. Current summary: "${currentText}"`
        : `You are a seasoned portfolio consultant and pitch specialist who knows that a project summary is often the first and only chance to capture someone's attention. Write a compelling 2-3 sentence summary for "${name}" - a ${projectContext}. Your summary must accomplish several things in very limited space: immediately establish what the project is and why it exists (the core purpose and problem being solved), clearly identify who it serves or impacts (target audience, users, or stakeholders), convey what makes it technically or creatively impressive (the unique approach, innovation, or challenge overcome), and communicate the tangible outcome or value created (what changed, improved, or was achieved).${techContext}${tagContext} Think of this as a verbal movie poster for your project - it needs to communicate genre, premise, and why someone should be interested, all in a glance. The language should be specific and vivid, avoiding vague claims. Use concrete details that make the project feel real and substantial. Keep it under 500 characters while packing maximum information and intrigue into every sentence.${urlContext}`,
    },
    {
      title: "Problem-solution",
      prompt: hasText
        ? `You are a business analyst and product storyteller who excels at framing projects in terms of the problems they solve. Restructure this summary for "${name}" (${projectContext}) to create a crystal-clear problem-solution narrative. Open by establishing the problem or pain point with enough specificity that readers immediately recognize its significance - who was affected, what were the consequences, why was this worth solving? Then transition powerfully into the solution, describing how "${name}" addressed this problem in a way that feels both innovative and inevitable. The connection between problem and solution should be so clear and compelling that readers think "of course that's exactly what was needed." Highlight what made this particular solution effective where others might have fallen short. Close with the resolution - how the solution changed the situation, what improved, and what was learned. This format is especially powerful for portfolio presentation because it demonstrates strategic thinking, not just technical execution. Current summary: "${currentText}"`
        : `You are a business analyst and product storyteller who knows that the most memorable project descriptions don't just describe what was built - they tell a story of a problem worth solving and a solution that made a difference. Write a problem-solution focused summary for "${name}" - a ${projectContext}. Structure your summary with narrative precision: begin by painting a vivid picture of the problem or challenge - be specific about who faced this problem, what the real-world consequences were, and why existing solutions or approaches were inadequate, present "${name}" as the deliberate, thoughtful response to this problem - explain the insight or approach that made this solution different and effective, describe the mechanism of the solution without getting lost in technical details - focus on how it worked from the user's or stakeholder's perspective, and conclude with the transformation - what the world looked like after this solution existed compared to before.${techContext} The summary should demonstrate that this project was not just technically executed, but strategically conceived - someone identified a real problem and built something that genuinely solved it. This shows the kind of thinking that separates senior professionals from those who just follow instructions.`,
    },
    {
      title: "Technical highlight",
      prompt: hasText
        ? `You are a senior technical architect and developer advocate who knows how to communicate technical excellence to both technical and non-technical audiences. Rewrite this summary for "${name}" (${projectContext}) to shine a spotlight on the technical sophistication and engineering achievements${stack ? `, particularly the use of ${stack}` : ""}. Your revision should convey technical depth without alienating non-technical readers. Highlight architectural decisions that were particularly elegant or impactful, interesting technical challenges that were overcome, and why specific technology choices were made over alternatives. Demonstrate not just what was built, but the engineering judgment behind it. The summary should make technical readers nod with respect while still being accessible enough that non-technical stakeholders understand why the technical approach matters. Use precise technical language where appropriate, but always connect it back to the project's value and outcomes. This is about showcasing engineering excellence, not just listing technologies used. Current summary: "${currentText}"`
        : `You are a senior technical architect and developer advocate who excels at communicating the "how" and "why" behind technical projects in a way that impresses both engineers and decision-makers. Write a technically-focused summary for "${name}" (${projectContext}) that showcases the engineering sophistication behind this project.${stack ? ` The project uses ${stack}, so your summary should` : ` Your summary should`} convey: the architectural approach and key technical decisions - what patterns, principles, or design philosophies guided the development, the interesting or challenging technical problems that were solved - scalability challenges, performance optimization, complex integrations, data modeling, or novel algorithms, the rationale behind key technology choices - why specific tools, frameworks, or platforms were selected over alternatives, and the technical outcomes or metrics that demonstrate engineering quality - performance benchmarks, reliability statistics, code quality metrics, or system capabilities. Write this for an audience that includes both technical peers who will appreciate the depth and non-technical stakeholders who need to understand why the technical approach was sound and valuable. Avoid buzzwords; every technical term should connect to a genuine engineering consideration. The summary should read like it was written by someone who deeply understands their craft.`,
    },
    {
      title: "Business impact",
      prompt: hasText
        ? `You are a business value consultant and ROI analyst who specializes in quantifying and communicating the business impact of technical projects. Reframe this summary for "${name}"${client ? `, built for ${client},` : ""} to focus squarely on business value, return on investment, and measurable organizational outcomes. Shift the narrative from "what we built" to "what value we created."${budget ? ` With a budget of $${budget.toLocaleString()}, it's important to demonstrate that this investment generated meaningful returns.` : ""} Quantify impact wherever possible: cost savings, revenue increases, efficiency gains, time reductions, user growth, satisfaction improvements, or competitive advantages gained. If specific metrics aren't available, describe the nature and scale of impact qualitatively but convincingly. Frame the project as a business asset that delivered concrete results, not just a technical exercise. The summary should speak directly to what executives, clients, and business stakeholders care about: did this project move the needle on something that matters? Show that you understand not just how to build, but why to build and how to measure success. Current summary: "${currentText}"`
        : `You are a business value consultant and ROI analyst who helps technical professionals communicate their work in the language of business impact. Write a business-impact-focused summary for "${name}" (${projectContext}) that speaks directly to the bottom-line value this project created.${budget ? ` The project had a budget of $${budget.toLocaleString()}, so your summary should frame this as an investment that delivered specific returns.` : ""} Structure the summary around value creation: start by identifying the business need or opportunity that justified this project - what was at stake? What was the cost of doing nothing? Describe the solution in terms of its business function and strategic role, not its technical features, quantify the impact using metrics that matter to business stakeholders: revenue generated or protected, costs reduced or avoided, efficiency gains (time saved, automation achieved), user or customer growth, market position improved, risk mitigated, or compliance achieved, and if possible, frame the return relative to investment - did this project pay for itself? In what timeframe?${client ? ` Since this was built for ${client}, consider what specific business value they derived.` : ""} The summary should demonstrate that you understand projects as business investments, not just technical endeavors. This perspective distinguishes senior professionals who can connect their work to organizational success.`,
    },
    {
      title: "Make shorter",
      prompt: hasText
        ? `You are a master of compression and verbal precision - an expert who can capture the soul of a complex project in a single, unforgettable sentence. Your task is to distill this summary for "${name}" (${projectContext}) into one powerful sentence that carries the full weight and significance of the project. This is the "elevator pitch" or "verbal logo" version - if someone asks what you built and you only have one breath to answer, this is what you say. To achieve this: identify the single most important thing to communicate about this project (purpose? impact? innovation? scale?), strip away everything that doesn't directly support that core message, use active, vivid language that creates a clear mental image, and ensure the sentence feels complete and satisfying - a full story compressed into its essence. The result should be so tight and powerful that it feels almost poetic in its efficiency. Think of how Apple describes products, how founders pitch to investors, how journalists write headlines. Every word must earn its place. Current summary: "${currentText}"`
        : `You are a master of verbal compression who can communicate the essence of complex projects in single, memorable sentences. Create a one-sentence elevator pitch for "${name}" - a ${projectContext}. This single sentence must accomplish what normally takes a paragraph: it should communicate what the project is, who it serves or impacts, and why it matters, all in one fluid, powerful statement. Use strong, specific verbs. Avoid relative clauses and dependent clauses that weaken impact. Front-load the most important information - don't bury the lede. The sentence should be quotable, memorable, and immediately create a clear picture in the listener's mind. It should work both in written form and when spoken aloud. Think of this as the sentence you'd put on the cover of a case study, the headline of a portfolio entry, or the answer you'd give when an interviewer says "tell me about your most impressive project" and you want to open with something that makes them lean forward. Avoid buzzwords, jargon (unless it adds precision), and filler phrases. Make every syllable count.`,
    },
    {
      title: "User-centric",
      prompt: hasText
        ? `You are a UX researcher and user advocate who believes that the best project descriptions center on the humans they serve. Rewrite this summary for "${name}" (${projectContext}) to put users at the heart of the narrative. Shift perspective from "what we built" to "what users experience and gain." Begin by identifying who the users are with specificity - not just "users" or "customers," but real human descriptions that create empathy. Describe their pain points, frustrations, or unmet needs in a way that makes readers feel why this project mattered on a human level. Then describe how "${name}" transforms their experience: what does it enable them to do that they couldn't before? How does it make them feel? What friction or frustration does it remove? Use concrete scenarios or micro-moments that illustrate the user experience. Close with the human impact - how users' lives, work, or capabilities are improved. This approach is particularly powerful for consumer products, internal tools, and any project where user adoption and satisfaction are key success metrics. Current summary: "${currentText}"`
        : `You are a UX researcher and user advocate who knows that behind every successful project are real people whose needs were understood and served. Write a user-centric summary for "${name}" (${projectContext}) that makes the humans in this story the protagonists. Structure the summary around the user journey: introduce the users with empathy and specificity - describe their context, goals, challenges, and what was at stake for them (avoid generic personas; describe real human situations that create relatability), articulate the gap between what users needed and what existed before "${name}" - what was the daily frustration, the workaround, the missed opportunity, or the inaccessible capability?, describe the experience of using "${name}" from the user's perspective - what does it feel like to interact with this solution? What moment of delight, relief, or empowerment does it create?, and show the transformation - how are users better off? What can they now do, achieve, or experience that they couldn't before?${tagContext} The summary should make readers feel the human value of this project, not just understand its features. This demonstrates empathy and user-centered thinking - qualities that distinguish great product builders from good ones.`,
    },
    {
      title: "Portfolio-ready",
      prompt: hasText
        ? `You are a hiring manager and creative director who reviews hundreds of portfolios and knows exactly what makes a project description stand out and compel an interview invitation. Polish this summary for "${name}" (${projectContext}) to be portfolio-ready - the kind of project description that makes recruiters pause, hiring managers take notes, and potential clients reach out. Your revision should exude professionalism, competence, and pride of craftsmanship. The tone should strike the perfect balance: confident without arrogance, detailed without being verbose, impressive without being exaggerated. Frame the project in terms of the skills it demonstrates and the professional growth it represents. Connect the work to broader industry relevance or trends where appropriate. The summary should make readers think "I want this person on my team" or "I want to hire this person for my project." It should showcase not just what was built, but what kind of professional you are - your standards, your thinking, your ability to deliver. Current summary: "${currentText}"`
        : `You are a hiring manager and creative director who has reviewed thousands of portfolios and can spot exceptional talent from a single project description. Write a portfolio-ready summary for "${name}" (${projectContext}) that positions this project as compelling evidence of professional capability. Your summary should be crafted for a dual audience: technical evaluators assessing skill level and non-technical decision-makers assessing professionalism and impact. It should communicate: the project's significance and why it was worth building (demonstrates judgment), your specific role and contribution (demonstrates ownership and capability),${stack ? ` the technical skills demonstrated through ${stack} (demonstrates hands-on expertise),` : ` the skills and technologies applied (demonstrates hands-on expertise),`} the challenges navigated and how they were overcome (demonstrates problem-solving and resilience), and the outcomes achieved or value delivered (demonstrates results-orientation). The tone should be professionally proud - like someone who did good work and knows it, but doesn't need to oversell. Avoid humble-bragging and false modesty; own your achievements directly and authentically. The summary should leave readers with a clear sense of what you're capable of and what it would be like to work with you. This is your professional reputation crystallized in a paragraph.`,
    },
    {
      title: "Add metrics",
      prompt: hasText
        ? `You are a data-driven product analyst and metrics specialist who believes that the most credible project descriptions are those backed by numbers. Enhance this summary for "${name}" (${projectContext}) by strategically incorporating relevant metrics and quantifiable results that prove the project's impact. Go beyond vague success claims and ground the narrative in specific, believable data. Consider metrics across multiple dimensions: user/audience metrics (number of users, growth rate, adoption percentage, retention), performance metrics (speed improvements, load times, throughput, availability), efficiency metrics (time saved, processes automated, error reduction, cost per unit), business metrics (revenue impact, cost savings, conversion rates, customer lifetime value), and quality metrics (test coverage, bug reduction, uptime, user satisfaction scores). Integrate metrics naturally into the narrative flow - they should enhance the story, not interrupt it with a disconnected list of numbers. Each metric should serve the narrative by proving a point about the project's success. Use specific numbers where available; use ranges or ballpark figures where exact numbers aren't known but can be reasonably estimated. Current summary: "${currentText}"`
        : `You are a data-driven product analyst and metrics specialist who knows that "successful project" is a claim, while "increased user engagement by 47% in the first quarter" is evidence. Write a metrics-driven summary for "${name}" (${projectContext}) that uses quantifiable results to tell a compelling story of measurable impact. Structure the summary so that metrics serve as proof points for key claims. For each important aspect of the project, ask "how would we measure success?" and incorporate relevant metrics. Consider these categories of metrics: scale metrics (how many users, transactions, data points, or requests does the system handle?), performance metrics (how fast, efficient, or responsive is it compared to alternatives or previous states?), impact metrics (what changed for users, the business, or the team - and by how much?), and quality metrics (how reliable, maintainable, or well-tested is the solution?).${techContext} The metrics should feel authentic and proportional - impressive but credible. If exact numbers aren't available, use descriptive ranges ("served thousands of users," "reduced processing time by an estimated 60-70%"). The goal is to transform the summary from a description of activities into a record of proven results. This approach signals a results-oriented professional who measures success and delivers impact.`,
    },
  ];
};

// Function to generate prompt options for project description
export const getProjectDescriptionPromptOptions = (
  formData: ProjectFormData,
  currentText: string,
): PromptOption[] => {
  const { project_name, project_category } = formData;

  // Return empty array if required fields are missing
  if (!project_name?.trim() || !project_category?.trim()) {
    return [];
  }

  const hasText = currentText.trim().length > 0;
  const name = project_name.trim();
  const category = project_category.trim();
  const stack = formData.stack?.length ? formData.stack.join(", ") : "";
  const tags = formData.tags?.length ? formData.tags.join(", ") : "";
  const client = formData.client_name?.trim();
  const budget = formData.budget;
  const summary = formData.project_summary?.trim();
  const url = formData.project_url?.trim();
  const dateRange = formData.start_date
    ? formData.end_date
      ? `from ${formData.start_date} to ${formData.end_date}`
      : `started ${formData.start_date}`
    : "";

  // Build context-rich description
  const projectContext = [
    category ? `${category} project` : "",
    client ? `for client ${client}` : "",
    budget ? `with a budget of $${budget.toLocaleString()}` : "",
    dateRange ? `(${dateRange})` : "",
  ]
    .filter(Boolean)
    .join(" ");

  const techContext = stack ? ` Built with: ${stack}.` : "";
  const tagContext = tags ? ` Key themes: ${tags}.` : "";
  const summaryContext = summary ? ` Project summary: "${summary}"` : "";

  return [
    {
      allowMarkdown: true,
      title: "Improve description",
      prompt: hasText
        ? `You are a technical documentation specialist and portfolio consultant who excels at transforming rough project notes into polished, comprehensive project descriptions that impress and inform. Rewrite this project description for "${name}" (${projectContext}) to create a well-structured, professional, and thorough project narrative. Your revision should: establish a clear, logical flow with distinct sections that guide the reader through understanding the project from concept to completion, use professional yet accessible language that works for both technical and non-technical audiences, balance technical depth with high-level clarity so that domain experts find substance while general readers stay engaged, incorporate all available context seamlessly${techContext}${summaryContext}, and demonstrate the sophistication of thinking behind the project - not just what was done, but why decisions were made and what was learned. Use markdown formatting to create visual structure with headings, subheadings, and well-organized paragraphs. The final description should read like a mini case study that any employer or client would find impressive and informative. Current description: "${currentText}"`
        : `You are a technical documentation specialist and portfolio consultant who knows that a great project description tells a complete story that demonstrates capability, judgment, and results. Write a comprehensive, well-structured project description for "${name}" - a ${projectContext}.${techContext}${tagContext}${summaryContext} Structure the description as a professional document with clear sections: **Overview** - a concise introduction that establishes what this project is, its purpose, and its significance, **Features & Capabilities** - a detailed breakdown of what the project does, its key functionalities, and what makes it valuable or unique, **Technical Implementation** - the architecture, technology stack, key technical decisions, and interesting engineering challenges solved, **Development Process** - the methodology, workflow, collaboration approach, and project management practices used, **Challenges & Solutions** - 2-3 significant obstacles encountered and how they were creatively or skillfully overcome, **Results & Impact** - the outcomes achieved, metrics where available, and the value delivered to users or stakeholders, and **Key Learnings** - skills developed, insights gained, and how this experience shaped professional growth. Use markdown formatting throughout to create a polished, readable document. The description should showcase not just the project, but the professional behind it - their thinking, standards, and capabilities.`,
    },
    {
      allowMarkdown: true,
      title: "Feature breakdown",
      prompt: hasText
        ? `You are a product manager and technical writer who specializes in creating clear, compelling feature documentation that helps readers understand what a product does and why each feature matters. Enhance this project description for "${name}" by adding a comprehensive feature breakdown section that systematically catalogs and explains the project's capabilities. For each feature: describe what it does in clear, user-focused language, explain its purpose - what problem it solves or what value it adds, provide brief implementation context that demonstrates technical understanding without overwhelming, and note any particularly elegant, innovative, or challenging aspects of its development. Organize features logically (by user flow, by system component, by priority, or by user role). The feature breakdown should demonstrate thoroughness and attention to detail while remaining engaging to read. Use markdown formatting with clear headings and bullet points for scannability. This section should make readers feel they truly understand the scope and capability of "${name}". Current description: "${currentText}"`
        : `You are a product manager and technical writer who excels at translating complex systems into clear, comprehensive feature documentation. Generate a detailed feature breakdown for "${name}" (${projectContext}).${techContext} For each major feature or capability, provide a thorough explanation covering: **Feature Name & Purpose** - what the feature does and why it exists (what user need or project goal it serves), **User Interaction / Functionality** - how users or systems interact with this feature, what the experience is like, and what outcomes it enables, **Technical Implementation** - how the feature was built, any interesting technical choices, integrations, or architectural considerations, and **Value Delivered** - what benefit this feature provides, how it contributes to the overall project goals, and what would be lost without it. Organize features in a logical hierarchy: group related features under thematic headings, use markdown formatting with nested headings and structured bullet points, and ensure the breakdown is comprehensive but not exhaustive - focus on features that best demonstrate capability and impact. The feature breakdown should showcase the breadth and depth of thinking that went into the project, demonstrating that features weren't just built, but thoughtfully designed to serve real needs.`,
    },
    {
      allowMarkdown: true,
      title: "Technical deep dive",
      prompt: hasText
        ? `You are a senior software architect and engineering blogger who excels at explaining complex technical systems with clarity, depth, and insight. Add a substantial technical deep dive section to this project description for "${name}"${stack ? ` covering ${stack}` : ""}. This section should go well beyond surface-level description and explore the technical foundations of the project with genuine depth. Cover: the overall system architecture - architectural pattern (microservices, monolith, serverless, event-driven, etc.), component relationships, and design rationale, data architecture - data models, database choices, data flow patterns, and any interesting data challenges solved, key technical decisions and trade-offs - what approaches were considered, what was chosen, and why (this demonstrates engineering judgment), API design and integration patterns - how different parts of the system communicate, external integrations, and interface design, and infrastructure and deployment - hosting, scaling strategy, CI/CD pipeline, monitoring, and operational considerations. Write this for a technical audience that will appreciate depth and precision. Use markdown code blocks for architecture diagrams (ASCII art), code snippets illustrating key patterns, or configuration examples. The deep dive should make another experienced developer think "this person really knows what they're doing." Current description: "${currentText}"`
        : `You are a senior software architect and engineering blogger who can explain complex technical systems in ways that are both deeply informative and engaging to read. Write a comprehensive technical deep dive for "${name}" (${projectContext}).${stack ? ` The stack includes ${stack}, and your deep dive should` : ` Your deep dive should`} explore the project's technical foundations with genuine engineering depth. Structure the deep dive to cover: **Architecture Overview** - the high-level system design, architectural patterns used, component decomposition, and the rationale behind structural decisions (include ASCII architecture diagrams in code blocks where helpful), **Technology Stack & Rationale** - detailed discussion of the technologies chosen, version considerations, why specific tools/frameworks/libraries were selected over alternatives, and how they work together, **Data Design** - database schema design, data modeling approach, data flow patterns, caching strategies, and how data consistency/integrity is maintained, **Key Technical Challenges** - the 2-3 most technically interesting problems encountered, the solution approaches explored, and the implemented solutions explained with enough detail that another engineer could understand the thinking, **API & Integration Architecture** - how the system communicates internally and externally, API design philosophy, authentication/authorization patterns, and integration with third-party services, and **Infrastructure & DevOps** - deployment architecture, CI/CD pipeline design, monitoring and observability setup, scaling considerations, and operational practices. Use markdown code blocks for code snippets, configuration examples, or terminal commands that illustrate key points. The deep dive should demonstrate senior-level engineering thinking and communication skills.`,
    },
    {
      allowMarkdown: true,
      title: "Challenges & solutions",
      prompt: hasText
        ? `You are an engineering leader and problem-solving storyteller who knows that the most impressive parts of any project description are the challenges overcome. Add a compelling "Challenges & Solutions" section to this project description for "${name}" that showcases resilience, creativity, and technical problem-solving. Identify 2-3 significant challenges that demonstrate different types of obstacles: technical challenges (performance issues, integration complexities, architectural problems), design challenges (UX difficulties, accessibility requirements, complex user flows), process challenges (tight deadlines, changing requirements, team coordination), or resource challenges (budget constraints, technical limitations, legacy system integration). For each challenge: describe the situation and what made it difficult (the "wall" you faced), explain the exploration process - what approaches were considered and rejected, and why, detail the solution implemented with enough specificity to demonstrate genuine problem-solving, and reflect on what was learned and how it influenced subsequent decisions. The challenges section should demonstrate that you don't just succeed when things go smoothly - you problem-solve effectively when they don't. Current description: "${currentText}"`
        : `You are an engineering leader and problem-solving storyteller who believes that how someone handles difficulty reveals more about their capability than how they handle success. Create a powerful "Challenges & Solutions" section for "${name}" (${projectContext}).${techContext} This section should present 2-3 significant challenges that showcase different dimensions of problem-solving ability. For each challenge, follow a narrative structure that builds tension and demonstrates resolution: **The Challenge** - vividly describe the obstacle encountered. What was the situation? What made this particularly difficult or critical? What was at stake if it wasn't solved? Be specific about the technical, design, or process constraints that made this a genuine challenge, **Exploration & Analysis** - describe the process of understanding and analyzing the problem. What root causes were identified? What potential solutions were explored? What research, prototyping, or consultation was done? This demonstrates analytical thinking and thoroughness, **The Solution** - detail the approach chosen and why it was selected over alternatives. Describe the implementation with enough technical specificity to be credible. Explain what made this solution effective, elegant, or innovative, and **Reflection & Impact** - what was the outcome of implementing this solution? What was learned from this challenge? How did this experience change your approach to similar problems in the future? This demonstrates growth and the ability to extract lessons from experience. The challenges should cover different types of obstacles (technical, design, process, resource) to show versatility in problem-solving. Write with the confidence of someone who faces challenges as opportunities to demonstrate capability.`,
    },
    {
      allowMarkdown: true,
      title: "Case study format",
      prompt: hasText
        ? `You are a management consultant and professional case study writer who transforms project descriptions into compelling business narratives. Restructure this description for "${name}" (${projectContext}) into a formal case study format that tells a complete, persuasive story of the project from inception to impact. A well-crafted case study follows a proven narrative arc that engages readers while systematically demonstrating value. Structure the content into these sections: **Executive Summary** - a high-level overview that hooks the reader and summarizes the entire story in one paragraph, **Background & Context** - the situation before the project, the organization or user context, and why this project became necessary, **Problem Statement** - a clear, specific articulation of the challenge, pain point, or opportunity that drove the project, **Approach & Methodology** - the strategic and methodological choices made, the process followed, and why this approach was suited to the problem, **Solution Overview** - what was built or implemented, described with enough detail to demonstrate substance, **Implementation Journey** - key moments, decisions, and pivots during development that shaped the final outcome, **Results & Impact** - quantified outcomes, stakeholder feedback, and the difference made, and **Key Takeaways** - lessons learned, insights gained, and how this experience informs future work. Use professional markdown formatting throughout. The case study should read like a document you'd present to a potential client saying "this is the kind of work we do and the results we deliver." Current description: "${currentText}"`
        : `You are a management consultant and professional case study writer who creates the kind of project narratives that win business and impress executives. Write a comprehensive case study for "${name}" (${projectContext}).${techContext}${summaryContext} A great case study is a persuasive document that proves capability through a real example. Structure it with these professionally formatted sections: **Executive Summary** - one paragraph that captures the entire story: the challenge, the solution, and the results. This is what busy decision-makers will read first (and sometimes only), **Background** - the context and situation. What organization, team, or user community was involved? What was the environment or landscape? What led to the need for this project?, **The Challenge** - a detailed articulation of the problem. Be specific about pain points, inefficiencies, missed opportunities, or competitive pressures. Quantify the cost of the problem where possible - this establishes the stakes, **Our Approach** - the methodology, process, and strategic thinking applied. Why was this approach chosen? What principles or frameworks guided decision-making? This demonstrates professional judgment, not just technical execution, **The Solution** - comprehensive description of what was built, implemented, or delivered. Include technical details that demonstrate sophistication while remaining accessible. Use diagrams, screenshots (described), or architecture overviews where helpful, **Results & Impact** - the outcomes achieved, quantified wherever possible. Include direct results (what the project achieved) and indirect impact (what those achievements enabled). Use metrics, testimonials (hypothetical placeholders), and before/after comparisons, and **Lessons Learned** - insights gained that demonstrate professional growth and the ability to extract generalizable knowledge from specific experience. Format the entire document with professional markdown: clear heading hierarchy, well-structured paragraphs, and strategic use of bold text for key points. The case study should serve as a powerful portfolio piece that says "this is what I'm capable of delivering."`,
    },
    {
      allowMarkdown: true,
      title: "Results focused",
      prompt: hasText
        ? `You are an impact measurement specialist and executive reporter who knows that results are the only part of a project description that truly matters to decision-makers. Rewrite this description for "${name}"${client ? ` for ${client}` : ""} to place results, outcomes, and measurable impact at the center of the narrative. Shift the entire framing from activity-focused ("we built X using Y") to impact-focused ("we achieved Z by building X"). Every section should connect back to the question "so what did that achieve?" Structure the description so that results aren't just a section at the end, but the theme that runs through the entire narrative. Use specific metrics wherever possible: performance improvements (load times, response times, throughput), user impact (adoption rates, satisfaction scores, task completion rates), business impact (revenue, cost savings, efficiency gains, market share), team impact (productivity improvements, reduced manual work, faster delivery cycles), and quality impact (reduced bugs, improved uptime, better maintainability). For each feature or component described, follow up with its result. This approach demonstrates that you build with outcomes in mind, not just for the sake of building. Current description: "${currentText}"`
        : `You are an impact measurement specialist and executive reporter who believes that projects are only as valuable as the results they produce. Write a results-focused project description for "${name}" (${projectContext}) where every aspect of the project is framed in terms of the outcomes and impact it achieved.${budget ? ` With a project budget of $${budget.toLocaleString()}, it's especially important to demonstrate the return on that investment.` : ""} Structure the entire description around a central question: "What changed because this project existed?" Organize content to continuously connect features, technical decisions, and process choices to the results they enabled: open with the most impactful results - lead with success rather than building up to it, for each major feature or capability described, immediately state the result or outcome it produced, demonstrate causal connections between technical decisions and business/user outcomes ("By choosing X architecture, we achieved Y performance improvement which enabled Z user experience"), use metrics aggressively but credibly - specific numbers where available, reasonable estimates where not, and measured language where neither is possible, and include different dimensions of results: technical outcomes (performance, reliability, maintainability), user outcomes (satisfaction, adoption, task success), business outcomes (revenue, savings, efficiency, competitive advantage), and professional outcomes (skills developed, capabilities demonstrated, reputation built).${client ? ` Since this was built for ${client}, consider what results would matter most to them and their stakeholders.` : ""} The description should leave no doubt that this project didn't just happen - it delivered value.`,
    },
    {
      allowMarkdown: true,
      title: "Process & methodology",
      prompt: hasText
        ? `You are an agile coach and development process expert who understands that how work gets done is often as important as what gets built. Add a detailed "Process & Methodology" section to this description for "${name}" that provides insight into your professional working approach. Cover the full development lifecycle and collaboration practices: project management methodology (Scrum, Kanban, Shape Up, or hybrid approaches) and why it was chosen for this type of project, sprint/iteration cadence and how work was planned, estimated, and tracked, team structure and collaboration patterns - how developers, designers, stakeholders, and clients worked together, development practices - code review processes, testing strategies (unit, integration, E2E), pair programming, documentation standards, version control workflow (Git branching strategy, commit conventions, PR templates), CI/CD pipeline - automated testing, build processes, deployment automation, and quality gates, and project management tools and communication practices - how progress was tracked, how decisions were documented, how stakeholders were kept informed. This section should demonstrate that you work professionally, systematically, and collaboratively - not as a solo coder hacking away in isolation. It shows you can integrate into professional teams and follow (or establish) effective processes. Current description: "${currentText}"`
        : `You are an agile coach and development process expert who knows that experienced professionals distinguish themselves not just by what they build, but by how they work. Write a comprehensive "Process & Methodology" section for "${name}" (${projectContext}) that documents the professional practices and workflows used throughout the project.${techContext} Structure this section to give readers a complete picture of your working approach: **Project Management** - the methodology used (Agile/Scrum/Kanban/Waterfall/Hybrid), sprint/iteration length, planning ceremonies, estimation techniques, and how work was prioritized and tracked, **Team & Collaboration** - team size and composition, roles and responsibilities, collaboration patterns (daily standups, async communication, pairing sessions), and how you interacted with stakeholders or clients, **Development Practices** - coding standards and conventions, testing strategy and coverage goals, code review process and quality standards, branching strategy and version control workflow, and documentation practices, **CI/CD & DevOps** - continuous integration setup, automated testing pipeline, deployment process and environments (dev/staging/production), monitoring and observability setup, and infrastructure as code or configuration management approach, and **Tools & Infrastructure** - the full toolchain used: project management tools, communication platforms, development environment, testing frameworks, deployment platforms, and monitoring solutions. This section should paint a picture of a disciplined, professional approach to software development. It demonstrates that you can operate effectively within established processes and make thoughtful choices about workflow and methodology.`,
    },
    {
      allowMarkdown: true,
      title: "Lessons learned",
      prompt: hasText
        ? `You are a reflective practitioner and professional development coach who believes that the ability to learn from experience is one of the most valuable professional traits. Add a thoughtful "Lessons Learned" section to this description for "${name}" that demonstrates self-awareness, intellectual honesty, and a growth mindset. Go beyond surface-level reflections ("I learned React") to explore deeper insights about the craft of software development, project execution, and professional growth. Consider: technical lessons - what did you learn about specific technologies, architectures, or approaches? What would you do differently technically?, process lessons - what worked well in your workflow and what didn't? How has your approach to planning, estimation, or collaboration evolved?, decision-making lessons - what decisions proved correct or incorrect? What would inform similar decisions differently in the future?, interpersonal lessons - what did you learn about working with stakeholders, clients, or team members? How has your communication or collaboration approach changed?, and personal insights - how did this project change you as a professional? What capabilities did you discover or develop? What do you now know about your strengths and areas for growth? Write with genuine reflection and honesty. Authentic lessons that acknowledge mistakes and growth are far more impressive than polished claims of perfection. Current description: "${currentText}"`
        : `You are a reflective practitioner and professional development coach who knows that the most impressive professionals are those who can articulate not just what they did, but what they learned and how they grew. Write a meaningful "Lessons Learned" section for "${name}" (${projectContext}).${techContext} This section should demonstrate the depth of your professional reflection and your commitment to continuous improvement. Structure the reflections to show genuine insight across multiple dimensions: **Technical Learnings** - what did this project teach you about the technologies used? What surprised you? What would you approach differently technically? What new capabilities did you develop? Be specific about tools, patterns, or techniques, **Architectural & Design Insights** - what did you learn about system design, trade-offs, or architectural decisions through this project? What patterns worked well? What would you restructure given hindsight?, **Process & Workflow Improvements** - how has this project influenced how you'll approach planning, estimation, development workflow, or project management in the future? What worked that you'll repeat? What didn't work that you'll avoid or modify?, **Collaboration & Communication Growth** - what did you learn about working with others (team members, stakeholders, clients, users)? How have your communication, expectation-setting, or collaboration skills evolved?, **Personal & Professional Development** - how did this project stretch you? What did you discover about your capabilities, preferences, or working style? What skills or qualities did you develop that you didn't have before?, and **What I'd Do Differently** - honest reflection on what you'd change if starting over. This isn't about regret; it's about demonstrating that you extract lessons from experience and apply them going forward. Write with authenticity and specificity. Generic "I learned a lot" statements signal shallow reflection. Specific insights about particular challenges, decisions, or moments of growth signal a thoughtful, self-aware professional who gets better with every project.`,
    },
    {
      allowMarkdown: true,
      title: "User story format",
      prompt: hasText
        ? `You are a UX designer and user researcher who specializes in communicating projects through the lens of the people they serve. Restructure this description for "${name}" around user stories, personas, and the human experience of the project. Shift from a system-centric perspective ("the application has feature X") to a human-centric perspective ("users can now accomplish Y, which means Z for their daily work"). Begin by defining the primary user personas with empathy and specificity - who are they, what is their context, what are their goals and frustrations? Then structure the description around key user journeys or stories that illustrate how different users interact with and benefit from "${name}". For each user story: describe the user's situation and need (the "As a... I want... so that..." format can be a starting point), walk through their experience - how they discover, access, and use the relevant features, and explain the transformation - how their situation improved, what they can now do, or how they feel. This format makes projects feel real and valuable because it connects features to human outcomes. Current description: "${currentText}"`
        : `You are a UX designer and user researcher who knows that the most compelling project descriptions don't talk about systems - they talk about people and how their experiences improved. Write a user-story-focused description for "${name}" (${projectContext}) that centers the narrative on the humans who interact with and benefit from this project.${tagContext} Structure the description as a collection of human-centered narratives: **User Personas** - introduce 2-3 primary user types with enough detail to create empathy. Describe their roles, contexts, goals, frustrations, and what they needed from a solution like "${name}". Give them names or descriptive titles to make them feel real, **Key User Journeys** - for each persona, describe a critical journey or workflow showing how they interact with the project. Use narrative storytelling: "When Sarah, a marketing manager, needs to analyze campaign performance, she previously had to... Now, with ${name}, she simply..." Show the before and after, **Pain Points Addressed** - explicitly map how the project's features correspond to specific user frustrations or needs. "Previously, users struggled with X because Y. We addressed this through Z, which means users now..." This demonstrates that features weren't built arbitrarily - they solve real problems, and **User Impact** - describe the tangible difference in users' daily experience. What tasks became easier, faster, or more enjoyable? What new capabilities do they have? How has their relationship with the problem domain changed? Write the entire description in a narrative, human-centered voice. Technical details should be mentioned in service of explaining how they improve the user experience, not as an end in themselves. This approach demonstrates empathy and user-centered thinking - qualities that distinguish professionals who build things people actually want to use.`,
    },
    {
      allowMarkdown: true,
      title: "Setup & deployment",
      prompt: hasText
        ? `You are a DevOps engineer and infrastructure specialist who understands that a project's operational details are crucial for demonstrating professional maturity. Add a comprehensive "Setup & Deployment" section to this description for "${name}" that covers the infrastructure, deployment, and operational aspects of the project. Include: hosting and infrastructure - where and how the project is hosted (cloud provider, specific services, server configuration), deployment process - the step-by-step deployment pipeline from code commit to production, including automation, environment strategy (development, staging, production) and how environments differ, configuration management - how environment variables, secrets, and configuration are managed securely, CI/CD details - the continuous integration and deployment setup, automated tests that run, build processes, and deployment triggers, monitoring and observability - how the health and performance of the project is tracked, alerting setup, logging strategy, domain and SSL configuration, and scaling considerations - how the infrastructure handles increased load, auto-scaling setup, performance optimization. If the project is open-source, include clear setup instructions that would allow another developer to get the project running locally: prerequisites, installation steps, environment configuration, and how to run the development server. This section demonstrates operational competence and the ability to ship and maintain production-grade software. Current description: "${currentText}"`
        : `You are a DevOps engineer and infrastructure specialist who knows that a project isn't complete until it's deployed, monitored, and maintainable. Write a thorough "Setup & Deployment" section for "${name}" (${projectContext}) that documents the operational infrastructure and deployment practices.${stack ? ` Given the ${stack} stack, cover:` : ` Cover:`} **Infrastructure & Hosting** - the hosting platform and services used (AWS/GCP/Azure/Vercel/Netlify/DigitalOcean/etc.), server configuration, database hosting, CDN setup, and domain/DNS configuration, **Deployment Pipeline** - the complete CI/CD workflow described step by step: what triggers a deployment (push to main, merge, tag), what automated processes run (linting, testing, building, security scanning), how the application is built and packaged, how it's deployed to different environments, and any post-deployment verification, **Environment Strategy** - the different environments (development, staging, production), how they differ in configuration and purpose, and how promotions between environments work, **Configuration & Secrets Management** - how environment variables are organized, how secrets and sensitive configuration are stored and accessed securely, and any configuration that varies between environments, **Monitoring & Observability** - the tools and practices for monitoring application health, performance, and errors, logging aggregation and search, alerting configuration for critical issues, and uptime/status monitoring, and **Local Development Setup** (especially important for open-source or team projects) - prerequisites and dependencies, step-by-step installation instructions, environment configuration for local development, how to run the development server and tests, and any additional tools or services needed locally. Include relevant code blocks for configuration files (Docker, docker-compose, CI config, environment examples), terminal commands, or infrastructure-as-code snippets. This section demonstrates that you understand and practice professional software delivery - you don't just write code, you ship and maintain it responsibly.`,
    },
  ];
};
