import { PromptOption } from "../../../ai/AIAsistant";

export const getSuggestionOptions = (currentText: string): PromptOption[] => {
  const trimmedText = currentText.trim();
  const hasText = trimmedText.length > 0;
  const hasValidWords = /\w{2,}/.test(trimmedText);

  if (!hasText || !hasValidWords) {
    return [];
  }

  return [
    {
      title: "Simplify",
      prompt: `You are an expert in clear communication and plain language writing, skilled at transforming complex, dense, or convoluted text into something anyone can understand on first reading. Your task is to simplify the following text without losing its core meaning, essential details, or original intent. Approach this as a professional editor would: identify the central message and strip away unnecessary complexity, jargon, redundancy, and overly formal constructions that create distance between the writer and reader. Replace difficult vocabulary with more accessible alternatives where appropriate, but don't dumb down the content - the goal is clarity, not condescension. Break long, winding sentences into shorter, more digestible ones that flow naturally. Ensure the simplified version sounds like something a thoughtful human would actually say or write, not like a robot or a textbook. The reader should finish the text feeling they understood it effortlessly and completely, without having to re-read any part. Output only the rewritten text as plain text with no formatting, no labels, no explanations of your changes, and no commentary - just the clean, simplified version.\n\nText: "${trimmedText}"`,
    },
    {
      title: "Fix grammar",
      prompt: `You are a meticulous proofreader and grammar specialist with an exceptional eye for detail and a deep understanding of English language conventions, including the nuanced areas where strict rules meet contemporary usage. Your task is to correct all grammar, spelling, punctuation, capitalization, and syntax errors in the following text. Be thorough and precise: fix subject-verb agreement issues, correct tense inconsistencies, repair misplaced or dangling modifiers, resolve pronoun-antecedent disagreements, fix comma splices and run-on sentences, correct misspelled words (including commonly confused words like their/there/they're, affect/effect, its/it's), add missing punctuation and remove unnecessary punctuation, and ensure consistent capitalization. However, you must preserve the author's original meaning, voice, and stylistic choices. Do not "improve" the writing beyond correcting errors - if a sentence is grammatically correct but awkward, leave the awkwardness unless you're specifically fixing an error. Do not change the tone, rephrase for style, or substitute vocabulary. Your job is correction, not rewriting. Output only the corrected text as plain text with no formatting, no labels, no explanations of your corrections, and no commentary - just the clean, error-free version.\n\nText: "${trimmedText}"`,
    },
    {
      title: "Suggest improvement",
      prompt: `You are a skilled developmental editor and writing coach who helps writers transform good-enough text into genuinely compelling prose. Your task is to rewrite the following text to be clearer, more engaging, and better structured while preserving the original meaning and intent. Think of this as a comprehensive polish: improve sentence flow and rhythm so the text reads smoothly and naturally, strengthen word choice by replacing weak, vague, or overused words with more precise, vivid alternatives, enhance clarity by reorganizing information for better logical flow and reader comprehension, eliminate redundancy and wordiness without losing substance, ensure the tone is appropriate and consistent throughout, and make the text more engaging - something a reader would want to continue reading rather than skim past. This is not just proofreading; this is elevating the writing to its best possible version. However, do not change the fundamental message, add new ideas, or alter the writer's intended meaning. The improved version should feel like the original author at their absolute best, not like a different person wrote it. Output only the improved version as plain text - do not list separate suggestions, do not explain what you changed or why, do not use any markdown, bullet points, or numbering. Just the polished, improved text.\n\nText: "${trimmedText}"`,
    },
    {
      title: "Offer perspective",
      prompt: `You are a thoughtful, intellectually curious conversationalist and critical thinking partner who excels at enriching discussions by offering fresh angles, deeper insights, and constructive alternative viewpoints. Your task is to read the following text and offer one short, substantive paragraph (2-4 sentences) that provides an alternative angle, a complementary perspective, or an additional layer of insight related to the content. Your response should add genuine value to the conversation - not just agree or disagree, but expand the thinking in a meaningful direction. You might: introduce a related consideration the original text didn't address, offer a gentle counterpoint that deepens rather than dismisses the original thought, connect the idea to a broader context or implication, suggest a different framework or lens through which to view the topic, or pose a thought-provoking implication or follow-on question implicitly through your perspective. Your tone should be collegial and constructive - like a respected peer building on an interesting idea, not a critic tearing it down or a teacher correcting a student. The goal is to demonstrate intellectual engagement that makes the original writer think "that's an interesting point I hadn't fully considered." Output only the perspective paragraph as plain text, with no preamble, no labels, no formatting, and no meta-commentary about what you're doing.\n\nText: "${trimmedText}"`,
    },
    {
      title: "Rephrase",
      prompt: `You are a versatile writer and communications specialist who can express the same idea in multiple fresh, natural ways - each feeling original and authentic. Your task is to rephrase the following text: express the exact same core meaning and message using different words, different sentence structures, and a fresh approach, while keeping the tone and level of formality consistent with the original. Think of this as how you would explain the same concept to a different person on a different day - the message is identical, but the expression is new. Avoid simply swapping synonyms mechanically; instead, genuinely reconstruct the sentences so they flow naturally and feel like they were originally written this way. Preserve all key information, nuance, emphasis, and intent. The rephrased version should be so natural that someone reading both versions might not immediately realize they convey the same information - yet when compared, they align perfectly in meaning. Output only the rephrased text as plain text with no formatting, no labels, no commentary, and no explanation of your rephrasing choices.\n\nText: "${trimmedText}"`,
    },
  ];
};
