// lib/promptOptions/skillPromptOptions.ts
import { PromptOption } from "../ai/AIAsistant";

// Function to generate prompt options for skill description
// Parameters match the actual fields available in EditSkillDialog
export const getSkillDescriptionOptions = (
  currentText: string,
  skillName: string,
  proficiencyLevel?: string,
  category?: string,
  subcategory?: string,
  difficultyLevel?: string,
  isMajor?: boolean,
): PromptOption[] => {
  // Return empty array if skill name is missing
  if (!skillName?.trim()) {
    return [];
  }

  const hasText = currentText.trim().length > 0;
  const skill = skillName.trim();
  const proficiency = proficiencyLevel || "Intermediate";
  const categoryName = category?.trim();
  const subcategoryName = subcategory?.trim();
  const difficulty = difficultyLevel?.trim();
  const isCoreSkill = isMajor ? "a core competency" : "a supporting skill";

  // Build context from available form fields
  const skillContext = [
    `${proficiency} level`,
    categoryName ? `in ${categoryName}` : "",
    subcategoryName ? `(${subcategoryName})` : "",
    difficulty ? `• ${difficulty} difficulty` : "",
    isCoreSkill,
  ]
    .filter(Boolean)
    .join(" ");

  const domainContext = [categoryName, subcategoryName]
    .filter(Boolean)
    .join(" - ");

  return [
    {
      title: "Improve description",
      prompt: hasText
        ? `You are an experienced hiring manager and professional skills evaluator who has reviewed thousands of skill descriptions. Rewrite the following skill description for ${skill} (${skillContext}) to make it dramatically more impactful, credible, and compelling. Your goal is to transform it into a description that immediately convinces readers of genuine, practical expertise - not just familiarity. Focus on demonstrating ${proficiency}-level proficiency through specific, concrete language that paints a picture of someone actively using this skill to deliver value. Replace vague claims like "experienced with" or "knowledge of" with action-oriented descriptions that show how the skill is applied, what level of complexity is handled, and what outcomes are achieved. The description should answer the unspoken questions in every evaluator's mind: "Can this person actually do the work? Have they solved real problems with this skill? What level of sophistication do they operate at?" Strike the perfect balance between confidence and credibility - impressive enough to stand out, specific enough to be believed. Current description: "${currentText}"`
        : `You are an experienced hiring manager and professional skills evaluator who has reviewed thousands of skill descriptions and knows exactly what separates an impressive one from a forgettable one. Write a compelling, authentic skill description for ${skill} (${skillContext}) that immediately establishes credibility and demonstrates real expertise. Your description should follow a proven structure: open with a strong statement of capability that sets the proficiency level clearly, describe the scope and complexity of work typically handled with this skill, provide concrete examples of how this skill has been applied in professional settings to solve problems or create value, convey the depth of understanding - not just what the person can do, but the principles and best practices they understand, and close with the impact or advantage this skill provides. ${isMajor ? "Since this is a core competency, emphasize mastery, strategic application, and how this skill differentiates them professionally. Show that this isn't just a skill they have, but a skill that defines their professional identity." : "Position this as a valuable supporting skill that enhances their core capabilities and adds versatility to their skill set."} Keep the description concise but substantive - every sentence should add meaningful information about capability level.`,
    },
    {
      title: "Technical depth",
      prompt: hasText
        ? `You are a technical subject matter expert and senior practitioner who specializes in ${skill}. Your task is to add genuine technical depth to this skill description that will resonate with both technical evaluators and savvy recruiters. Go deep - mention specific tools, frameworks, versions, libraries, methodologies, or technical concepts that someone at ${proficiency} level would reasonably know and work with. Demonstrate an understanding of not just what tools are used, but the underlying principles, trade-offs, and best practices. Reference industry-standard approaches, design patterns, or workflows relevant to ${domainContext || skill}. The enhanced description should signal to other technical professionals that this person truly understands the craft - they know the ecosystem, they've made informed technical decisions, and they operate at a level beyond surface-level tool usage. Use precise technical language that would earn a nod of recognition from a senior practitioner in the field. Avoid buzzwords and generic claims; every technical reference should serve as proof of genuine hands-on experience. Current description: "${currentText}"`
        : `You are a technical subject matter expert and senior practitioner with deep expertise in ${skill}${domainContext ? ` within the ${domainContext} domain` : ""}. Create a technically rich and detailed skill description that convincingly demonstrates ${proficiency}-level mastery. Your description should demonstrate depth through precision: name specific tools, frameworks, technologies, versions, and methodologies that someone at this level would have hands-on experience with, show understanding of the ecosystem - complementary tools, common integrations, development workflows, or industry-specific applications, reference relevant technical concepts, architectural patterns, or best practices that indicate theoretical knowledge backing practical skills, distinguish between different approaches or schools of thought within the field and indicate informed preferences, and hint at the complexity of problems this person can solve - the scale of systems, the difficulty of challenges, or the sophistication of solutions they handle. The description should be written at a level where another ${skill} practitioner would read it and think "this person knows what they're talking about" rather than "this is someone who read the Wikipedia article." Be specific, be accurate, and let the technical vocabulary naturally demonstrate expertise rather than claim it.`,
    },
    {
      title: "Achievement-focused",
      prompt: hasText
        ? `You are a career strategist who understands that the most powerful skill descriptions are those that connect capabilities to concrete results. Transform this skill description by infusing it with specific achievements, measurable outcomes, and tangible impacts delivered through ${skill} (${skillContext}). Your revision should shift from describing what someone knows to demonstrating what they've accomplished. For each capability mentioned, ask "so what?" and answer with the result. Incorporate metrics and specifics wherever plausible: percentage improvements, time saved, revenue generated, users impacted, systems optimized, projects delivered, teams led, or problems resolved. The achievements should feel authentic and proportional to ${proficiency} level - impressive but believable for someone at this stage of their career. Use the CAR framework implicitly (Challenge - Action - Result) to structure achievement statements: what was the situation, how was ${skill} applied, and what measurable difference did it make? The final description should read like a highlight reel of proven performance, making it impossible for evaluators to doubt the practical value of this expertise. Current description: "${currentText}"`
        : `You are a career strategist and executive resume writer who knows that the most compelling skill descriptions don't just list capabilities - they prove impact through specific, quantified achievements. Write an achievement-driven description for ${skill} as ${isCoreSkill} (${proficiency} level). Structure the entire description around the results this skill has produced, not just the activities it involves. Your description should include: at least 2-3 specific achievement statements that follow an implicit "challenge → action → result" structure, concrete metrics and measurable outcomes that are realistic and proportional to ${proficiency} level experience, the scope and scale of impact (size of teams, budgets, user bases, systems, or organizations affected), any recognition, awards, promotions, or special assignments that resulted from expertise in this skill, and qualitative impacts where quantitative metrics aren't applicable - transformations enabled, problems permanently solved, or capabilities built for organizations. The achievements should span different dimensions: efficiency gains, quality improvements, innovation contributions, revenue impact, or team/organizational development. Write with the confidence of someone who has a track record of delivering results, not someone hoping to impress with inflated claims. Make every achievement statement feel verified and substantial.`,
    },
    {
      title: "Project application",
      prompt: hasText
        ? `You are a project storyteller and portfolio consultant who excels at translating technical skills into vivid, concrete narratives of real-world application. Reframe this skill description to showcase how ${skill} has been applied in actual projects${domainContext ? ` within ${domainContext}` : ""} at ${proficiency} level. Paint a picture of the practitioner in action - what kinds of projects they've worked on, what specific challenges they've tackled, what their role was, and what outcomes they delivered. Use project-based language that creates mental images of real work: "led the migration of...", "architected a solution for...", "implemented... to solve...", "optimized... resulting in...". Describe the types of problems this person is equipped to solve and the complexity of projects they can handle. Include enough context about the project environments to make the application feel real - team sizes, timelines, stakes, constraints. The description should make readers think "I can clearly picture how this person would contribute to our projects" rather than just "they have a skill on their resume." Current description: "${currentText}"`
        : `You are a project storyteller and portfolio consultant who knows that the most convincing skill descriptions show the skill in action rather than just naming it. Create a vivid, project-centric description of ${skill} (${skillContext}) that brings the practitioner's experience to life through concrete scenarios and applications. Your description should function like a mini-portfolio: open by establishing the types of projects and contexts where this skill has been applied (industry, scale, complexity), describe 2-3 specific project scenarios that demonstrate different dimensions of the skill - include the challenge faced, the approach taken using ${skill}, and the resolution achieved, show range by covering different types of applications (e.g., greenfield projects, optimizations, rescue missions, innovations, or team leadership roles), convey the level of autonomy and responsibility typical at ${proficiency} level (supervised, independent, leading others, setting strategy), and close with the types of project challenges this person is now equipped and eager to take on. Use active, narrative language that creates scenes: "When the legacy system began failing under load, they...", "For a high-stakes client launch, they...", "Recognizing an opportunity to improve...". The description should read like compelling evidence of hands-on capability, not a theoretical knowledge summary.`,
    },
    {
      title: "Core competency",
      prompt: hasText
        ? `You are a personal branding strategist who helps professionals articulate not just what skills they have, but what skills define them. Rewrite this description to powerfully communicate why ${skill} is ${isCoreSkill}${domainContext ? ` in ${domainContext}` : ""}. ${isMajor ? "This is a foundational skill that shapes their professional identity - the description should convey strategic importance, deep investment, and how this skill differentiates them in the marketplace. Go beyond technical capability to express a professional philosophy or unique approach that sets them apart from others with similar technical skills." : "This skill enhances and complements their core strengths - the description should show how it adds versatility, rounds out their capabilities, and enables them to operate more effectively across different contexts. Emphasize synergy with other skills and the unique combination of capabilities it creates."} The revised description should make it clear why this particular skill matters in their professional story and what would be lost if they didn't have it. Make the strategic value of this competency unmistakable. Current description: "${currentText}"`
        : `You are a personal branding strategist who understands that skills aren't just items on a list - they form a narrative about what makes a professional unique and valuable. Write a description that positions ${skill} as ${isCoreSkill}${domainContext ? ` within the ${domainContext} domain` : ""}. ${isMajor ? `This is a defining competency - the kind of skill that shapes careers and differentiates top performers. Your description should accomplish several things: articulate why this skill is foundational to their professional identity and value proposition, convey not just proficiency but a distinctive approach or philosophy that sets them apart from others with similar technical capability, show how this skill has been a thread through their career - growing, deepening, and enabling greater contributions over time, demonstrate strategic thinking about how and when to apply this skill for maximum impact, and position them as someone who doesn't just possess this skill, but contributes to advancing it - through mentoring, best practices, thought leadership, or innovation. The description should make the reader feel that this isn't just a skill they checked off a list; this is a skill they've built a career around.` : `This is a valuable supporting competency that enhances versatility and effectiveness. Your description should: show how this skill complements and amplifies their primary expertise, creating a unique combination of capabilities, demonstrate the additional value, perspective, or capability this skill brings to their core work, provide examples of how this skill has enabled them to bridge gaps, solve interdisciplinary problems, or operate more effectively in cross-functional contexts, and convey that while this may not be their primary identity, they've invested seriously in developing it and apply it with genuine competence. The description should position this skill as a force multiplier - it makes everything else they do more effective.`}`,
    },
    {
      title: "Learning journey",
      prompt: hasText
        ? `You are a professional development storyteller who understands that the most authentic and compelling skill descriptions acknowledge growth and progression. Transform this description to tell the story of ${skill} expertise development${difficulty ? ` through increasingly ${difficulty.toLowerCase()} concepts` : " over time"}. Show the trajectory from early learning to current ${proficiency} level capability. Include: how they initially encountered or developed this skill, key milestones or breakthrough moments in their learning journey, challenges overcome and how they pushed through plateaus,${difficulty ? ` how they progressed from foundational to ${difficulty.toLowerCase()} concepts and applications,` : ""} and what continuous learning or skill advancement looks like now. This narrative approach makes the expertise feel earned and genuine rather than claimed. It also demonstrates growth mindset, perseverance, and self-awareness - qualities that are often as important as the skill itself. The description should read like a professional reflecting thoughtfully on their development, not just stating their current level. Current description: "${currentText}"`
        : `You are a professional development storyteller who believes that showing how someone learned something is often more impressive than just stating what they know. Create a narrative skill description that chronicles the development of ${skill} expertise to its current ${proficiency} level${difficulty ? ` (encompassing ${difficulty.toLowerCase()} difficulty concepts)` : ""}. Structure this as a mini professional journey: begin with the origin - how and why they started developing ${skill} (a project need, intellectual curiosity, career pivot, mentorship opportunity), describe the progression through increasing levels of complexity - early wins, foundational projects, growing confidence, and expanding scope, highlight 2-3 key milestones that marked significant leaps in capability (a challenging project mastered, a certification achieved, a complex problem solved, a transition from learner to teacher), acknowledge challenges honestly - what was difficult to learn, what misconceptions they had to overcome, where they had to persist through frustration,${difficulty ? ` show how they specifically tackled ${difficulty.toLowerCase()}-level concepts - what resources, projects, or mentorship helped them master these advanced areas,` : ""} and describe the current state of learning - how they continue to develop, what they're currently exploring, and where they see the skill evolving. This approach demonstrates not just expertise, but the valuable meta-skills of learning, persistence, and self-directed growth that employers deeply value.`,
    },
    {
      title: "Make concise",
      prompt: hasText
        ? `You are a master editor who specializes in creating maximum impact with minimum words. Your task is to compress this ${skill} description (${skillContext}) into a tight, powerful statement of just 2-3 sentences that hits harder than the original. Apply ruthless prioritization: identify the absolute most important and differentiating aspects of this expertise, eliminate all redundancy, filler phrases, and supporting details that are nice but not essential, compress complex ideas into punchy, memorable phrasing, and ensure every remaining word carries weight and communicates something valuable. The condensed version should function as a verbal business card for this skill - if someone only reads one thing about their ${skill} capability, this should be it. It must convey proficiency level, key applications, and what makes their expertise distinctive, all in one breath. Think of this as the "headline version" that someone would remember and repeat when describing this person's capabilities to others. Current description: "${currentText}"`
        : `You are a master of concise professional communication who can distill complex expertise into its most potent essence. Create an ultra-impactful 2-sentence description for ${skill} (${skillContext}) that captures everything that matters most about this capability. Sentence one should establish: proficiency level, primary domain of application, and core capability in the most direct language possible. Sentence two should add: what makes their expertise distinctive, the primary value or outcome it delivers, or the highest-level application they're capable of. Think of this as the description that would appear under their name on a conference speaker card or in a "Top Experts in ${skill}" feature - it needs to command attention and convey substance instantly. Use active, confident language. Avoid: filler phrases ("has experience with", "knowledgeable in", "familiar with"), weak qualifiers ("somewhat", "fairly", "relatively"), and any word that doesn't directly contribute to proving expertise or impact. Every word must earn its place.`,
    },
    {
      title: "ATS optimization",
      prompt: hasText
        ? `You are an ATS (Applicant Tracking System) optimization specialist and recruitment technology expert who understands exactly how automated systems parse, score, and rank skill descriptions. Optimize this skill description for maximum ATS performance while keeping it completely natural and compelling for human readers. Your optimization strategy: identify and naturally incorporate the most important keywords and phrases that ATS systems and recruiters search for when looking for ${skill} expertise${domainContext ? ` in ${domainContext}` : ""}, include both primary keywords and semantic variations (synonyms, related terms, alternative phrasings) that demonstrate comprehensive coverage of the skill space, structure content to align with standard industry taxonomies and skill frameworks commonly used in recruitment systems, integrate relevant tools, technologies, methodologies, and certifications that serve as additional search triggers, and ensure keyword density feels organic - never stuff keywords at the expense of readability, as many modern ATS systems penalize obvious optimization attempts. The optimized description should read so naturally that a human would never suspect it was ATS-tuned, while containing all the signals that make algorithms rank it highly. Context: ${skillContext}. Current text: "${currentText}"`
        : `You are an ATS (Applicant Tracking System) optimization specialist who understands the technical architecture of recruitment platforms and the search behaviors of both algorithms and human recruiters. Generate an ATS-optimized skill description for ${skill} (${skillContext}) that will rank highly in automated screening while impressing human evaluators. Your description must satisfy both audiences simultaneously: for the algorithms, strategically incorporate primary search keywords and their common variants that recruiters use to find ${skill} expertise${domainContext ? ` within ${domainContext}` : ""}, include related tools, platforms, methodologies, and industry-standard terminology that expand keyword coverage naturally, align with common skills taxonomies and categorization frameworks used by major ATS platforms (Workday, Greenhouse, Lever, etc.), use both full terms and common abbreviations/acronyms appropriately, and maintain a keyword density that optimizes for search without triggering spam filters or keyword-stuffing penalties. For the humans, read as a natural, fluent, and compelling description written by a real professional - not an SEO exercise, demonstrate genuine understanding through context-appropriate usage of terms (not just dropping keywords), and maintain the warm, confident voice of someone describing their actual expertise. The ultimate test: a recruiter should read it and think "strong candidate" while the ATS simultaneously scores it as a high-match for relevant searches. Provide the description only, with no visible optimization artifacts, keyword lists, or meta-commentary.`,
    },
  ];
};
