import { PromptOption } from "../../../ai/AIAsistant";

interface BioContext {
  currentText?: string;
  profession?: string;
  jobTitle?: string;
  yearsOfExperience?: string;
  availability?: string;
  openToWork?: boolean;
}

// Function to generate prompt options with context of existing bio
export const getBioPromptOptions = (
  context: BioContext = {},
): PromptOption[] => {
  const {
    currentText = "",
    profession,
    jobTitle,
    yearsOfExperience,
    availability,
    openToWork,
  } = context;

  // Return empty array if any non-context fields lack value
  if (!profession || !jobTitle || !yearsOfExperience) {
    return [];
  }

  const hasText = currentText.trim().length > 0;

  // Build context string for prompts
  const buildContextString = () => {
    const parts: string[] = [];
    if (profession) parts.push(`my profession: ${profession}`);
    if (jobTitle) parts.push(`my job title: ${jobTitle}`);
    if (yearsOfExperience)
      parts.push(`my years of experience: ${yearsOfExperience}`);
    if (availability) parts.push(`my availability: ${availability}`);
    if (openToWork !== undefined)
      parts.push(`I am open to work: ${openToWork ? "yes" : "no"}`);
    return parts.join(", ");
  };

  const contextString = buildContextString();

  return [
    {
      allowMarkdown: true,
      title: "Professional bio",
      prompt: hasText
        ? `You are an expert personal branding strategist and professional copywriter. I need you to completely rewrite and elevate my professional bio to make it significantly more polished, impactful, and compelling. Your task is to transform it into a powerful narrative that immediately captures attention and establishes my credibility. Focus on creating a strong opening hook, weaving in my unique value proposition, showcasing my expertise in ${profession} as a ${jobTitle} with ${yearsOfExperience} of experience, and ending with a memorable closing statement. The tone should be confident but not arrogant, professional but not stiff, and highlight both my technical capabilities and human qualities. Ensure the language is active and dynamic, avoiding passive constructions and generic buzzwords. Write entirely in first person using "I," "me," and "my" throughout. Format your response using proper markdown with clear paragraph breaks, bold text for key achievements or roles, and italic emphasis for impactful statements where appropriate. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are an expert personal branding strategist and professional copywriter. Generate a comprehensive and captivating professional bio for me. I am a ${jobTitle} with ${yearsOfExperience} of experience in ${profession}. Craft a compelling first-person narrative that opens with a powerful hook, establishes my authority and unique perspective in the field, showcases my professional journey and key milestones, highlights my core strengths and specialized expertise, and concludes with my professional philosophy or vision. The bio should feel authentic, sophisticated, and memorable - the kind that makes recruiters and potential clients immediately want to learn more about me. Avoid clichés and generic statements; instead focus on what makes me truly exceptional in my role. Write entirely in first person using "I," "me," and "my." Format your response using proper markdown: use **bold** to highlight my job title and key strengths, *italics* for memorable phrases, and well-structured paragraphs with clear line breaks between them. Keep it under 2000 characters. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Make concise",
      prompt: hasText
        ? `You are a master editor specializing in professional communications. Take my following bio and distill it down to its absolute essence - I want the most powerful, punchy version possible in just 2-3 tightly crafted sentences. Every word must earn its place. Your goal is to create a "mic drop" bio that instantly communicates who I am, what I do, my unique edge as a ${jobTitle} in ${profession}, and why it matters - all in one breath. Cut all filler, eliminate redundancies, and replace weak language with vivid, action-oriented alternatives. Think of this as my verbal business card or the one thing I'd say if I only had 15 seconds to impress my dream employer. Write entirely in first person using "I," "me," and "my." Format your response using markdown: use **bold** to emphasize my role and key differentiator, and separate the sentences with clear line breaks for visual impact. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a master editor specializing in professional communications. Create a razor-sharp, ultra-concise professional bio (2-3 sentences maximum) for me. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience. This needs to be my "elevator pitch on paper" - the distilled essence of my professional identity that hits hard and leaves a lasting impression. Every word must pull double duty: conveying information while building intrigue. Start with my role and core differentiator, follow with a key achievement or capability that proves my expertise, and close with the impact I create or the problems I solve. Think of this as what would appear under my name at a TED talk or in a featured industry spotlight. Write entirely in first person using "I," "me," and "my." Format your response using markdown: use **bold** for my job title and standout metrics, and separate each sentence with a new paragraph for dramatic effect. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Make detailed",
      prompt: hasText
        ? `You are a professional biographer and narrative storyteller who specializes in crafting rich, multidimensional professional profiles. Take my current bio as a foundation and expand it into a comprehensive, compelling professional narrative about me. I want you to add depth, texture, and personality while maintaining absolute professionalism. Explore my journey as a ${jobTitle} in ${profession} - include my formative experiences, pivotal career moments, philosophy of work, approach to challenges, and vision for my field. Weave in my specific achievements and their significance, key skills and how I've applied them, my professional values, and what drives my passion for ${profession}. The expanded bio should feel like a well-crafted story where the reader walks away feeling they truly understand my professional journey, capabilities, and unique perspective. Write entirely in first person using "I," "me," and "my." Format your response using rich markdown: use **bold** for key roles, achievements, and milestones; *italics* for personal philosophies and memorable quotes; well-structured paragraphs with clear line breaks; and consider using bullet points or numbered lists for my key achievements or skills if it enhances readability. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a professional biographer and narrative storyteller who specializes in crafting rich, multidimensional professional profiles. Create a detailed, narrative-driven professional bio for me. I am a ${jobTitle} with ${yearsOfExperience} in ${profession}. Go beyond surface-level credentials to paint a complete picture of me as a dedicated professional: my origin story and what drew me to this field, the evolution of my expertise over ${yearsOfExperience}, landmark projects or achievements that showcase my growth, my professional methodology and approach to problem-solving, the impact I've had on organizations, teams, or clients, my thought leadership or unique perspectives on ${profession}, and my aspirations or the legacy I'm building. The bio should be substantive and sophisticated, reading like a featured profile in an industry publication. Write entirely in first person using "I," "me," and "my." Format your response using comprehensive markdown: use **bold** for key roles, companies, and standout achievements; *italics* for my personal philosophy and guiding principles; well-spaced paragraphs with clear breaks; and bullet points or numbered lists where appropriate to highlight my key milestones or areas of expertise. Keep it under 2000 characters. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Add achievements",
      prompt: hasText
        ? `You are a results-focused career strategist and executive resume writer. Transform my bio into a compelling, achievement-driven professional summary that quantifies my impact and demonstrates my proven excellence. Your mission is to infuse the narrative with my concrete accomplishments, measurable results, and tangible proof of my expertise as a ${jobTitle} in ${profession}. For each capability mentioned, ask "what was the result?" and incorporate that evidence seamlessly into my storytelling. Use powerful metrics (percentages, dollar amounts, time saved, teams led, revenue generated, efficiency improvements) to create a track record of my undeniable success. The bio should make readers think "this person doesn't just do the job, they deliver exceptional results." Format my achievement highlights naturally within the narrative flow, not as a bulleted list. Write entirely in first person using "I," "me," and "my." Format your response using markdown: use **bold** to highlight key metrics and results (e.g., **increased revenue by 40%**, **led a team of 25**), *italics* for the impact statements, and ensure proper paragraph structure with line breaks for readability. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a results-focused career strategist and executive resume writer. Generate a powerful, achievement-laden professional bio for me. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience. This bio must be built around a foundation of my concrete accomplishments, quantified impacts, and demonstrated excellence. Structure it around my key result areas: business impact and value creation, innovation and problem-solving wins, leadership and team development successes, client or stakeholder transformations, and professional recognition or industry contributions. For each area, craft compelling narrative statements that incorporate specific, believable metrics and outcomes that would be impressive for someone at my level and tenure. The bio should read as a highlight reel of my career-defining moments that prove I am in the top percentile of my field. Use confident, active first-person language that conveys both my competence and ambition. Write entirely in first person using "I," "me," and "my." Format your response using strategic markdown: use **bold** to make all metrics and achievements stand out prominently, *italics* to emphasize the significance of results, and well-structured paragraphs with line breaks. Consider using bullet points with bold lead-ins if it makes the achievements more scannable. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Casual tone",
      prompt: hasText
        ? `You are a conversational copywriter who specializes in making professional profiles feel human, warm, and genuinely relatable. Rewrite my bio in a casual, approachable, and authentic voice that feels like I'm describing what I do to a new friend over coffee - professional enough to be taken seriously, but personal enough to be memorable and likable. Strip away corporate stiffness, buzzwords, and formal pretenses. Instead, bring out my personality, share what genuinely excites me about being a ${jobTitle} in ${profession}, mention what my typical day looks like in a relatable way, hint at my work style and what it's like to collaborate with me, and include a touch of humor or warmth where appropriate. The reader should feel like they're getting to know me as a real person, not reading a corporate document. Write entirely in first person using "I," "me," and "my." Format your response using markdown: use **bold** for emphasis on key phrases and my core passion, *italics* for more subtle emphasis or humor, em dashes (—) for natural conversational pauses, and relaxed paragraph breaks that mirror natural speech patterns. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a conversational copywriter who specializes in making professional profiles feel human, warm, and genuinely relatable. Create a casual, authentic professional bio for me. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience. Write it as if I'm introducing myself at a relaxed networking event or writing my "about me" for a creative portfolio site. The tone should be warm, approachable, and slightly informal while still conveying my competence and professionalism. Include elements like: what I love most about my work, a brief anecdote or insight that reveals my personality, what drives me beyond just the job title, the kinds of problems I enjoy solving, and the types of people or projects I'm most excited to work with. Make it feel like the start of a great professional relationship rather than a sterile credential list. Use contractions, varied sentence lengths, and a natural conversational rhythm. Write entirely in first person using "I," "me," and "my." Format your response using markdown: use **bold** for emphasis on exciting projects or passions, *italics* for personal anecdotes or asides, em dashes (—) for natural pauses, and short, punchy paragraphs that feel conversational. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Open to work",
      prompt: hasText
        ? `You are a career transition strategist and recruitment marketing specialist. Revise my bio to strategically and compellingly signal that I am actively open to new opportunities, while maintaining my value and positioning me as a highly desirable candidate. As a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience, I bring significant expertise to the table. My updated bio should: naturally weave in my openness to the right opportunity without sounding desperate or junior, include a subtle but clear call-to-action that invites the right kinds of outreach (specific roles, industries, or collaboration types), frame my job search as a strategic career move driven by ambition and readiness for greater impact, and maintain my authority and thought leadership position throughout. The language should position me as a sought-after professional exploring my next chapter, not someone simply looking for any job. Write entirely in first person using "I," "me," and "my." Format your response using strategic markdown: use **bold** to highlight my core expertise and the types of opportunities I'm seeking, *italics* for my career philosophy, and ensure the call-to-action stands out clearly with proper spacing. Consider using a horizontal rule (---) to separate my experience section from the open-to-work call-to-action if it enhances the structure. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a career transition strategist and recruitment marketing specialist. Create a compelling professional bio for me. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience, and I want to strategically communicate that I am open to new work opportunities. The challenge is to signal my availability while maintaining premium positioning - I'm not just job seeking, I'm selectively exploring my next impactful role. Craft a bio that: establishes my expertise and track record upfront to build immediate credibility, gracefully transitions into my current career exploration, frames my availability as a limited-time opportunity for the right organization to secure top talent (me), specifies the types of opportunities, challenges, or industries I'm most excited about, includes a warm but professional invitation to connect or reach out to me, and maintains an optimistic, forward-looking tone that suggests exciting things ahead. The overall impression should be "this is someone you'd be lucky to hire" not "someone who needs a job." Write entirely in first person using "I," "me," and "my." Format your response using strategic markdown: use **bold** to make the call-to-action and my target opportunities prominent, *italics* to convey enthusiasm, and ensure clear structural separation between my experience section and the open-to-work messaging. Consider using a horizontal rule (---) or clear headers to distinguish sections for maximum visual impact. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "LinkedIn headline",
      prompt: hasText
        ? `You are a LinkedIn optimization expert and personal branding strategist. Transform the essence of my bio into a scroll-stopping LinkedIn headline that commands attention in a crowded feed and compels profile clicks. You have exactly 220 characters to work with, and every character must earn its place. My headline must: lead with a powerful, keyword-rich title that immediately communicates my ${jobTitle} role and ${profession} expertise, incorporate my ${yearsOfExperience} of experience in a compelling way, include my unique value proposition or specialty that differentiates me, naturally embed high-value keywords recruiters and clients search for, and end with either a results statement or a forward-looking declaration about what I deliver. Use proven headline formulas: vertical bars (|), em dashes, or strategic formatting to pack maximum information cleanly. Study my original bio for unique angles and achievements to feature. Write the headline in first person where appropriate, using "I" statements. Format the final headline using markdown: present it as a bold headline using **bold text** and ensure it's on its own line with proper spacing. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a LinkedIn optimization expert and personal branding strategist. Create a magnetic, search-optimized LinkedIn headline for me. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience. My 220-character masterpiece must accomplish multiple objectives simultaneously: instantly communicate my professional identity and seniority level, feature my primary area of expertise and any specialized niche, incorporate industry-relevant keywords that improve my searchability for recruiters and potential clients, convey my unique value proposition or what makes my approach different, and create intrigue that drives profile visits. Use strategic formatting with separators (|, •, —, or →) to organize information cleanly and create visual rhythm. The headline should work as hard as a 30-second elevator pitch, telling viewers exactly who I am, what I do, and why I matter. Consider including: my role + specialization + key achievement metric + target audience or mission. Write the headline in first person where appropriate. Format the final headline using markdown: present it prominently using **bold text** on its own line, and if breaking down elements, use a clean markdown structure to display the headline components clearly. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "First person",
      prompt: hasText
        ? `You are a ghostwriter specializing in authentic first-person professional narratives. Transform my bio into a warm, personal, first-person account that feels like I'm speaking directly to the reader. Write entirely using "I," "me," and "my" statements. As a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience, my voice should convey both competence and genuine human connection. My narrative should: open with my personal mission statement or the "why" behind my work, share my professional philosophy and approach in my own voice, reflect on my key experiences and what I learned from them, express my genuine enthusiasm for ${profession} and the problems I solve, and close with an invitation for connection or collaboration. The tone should be confident yet humble, experienced yet still curious, professional yet deeply personal. Readers should feel like they just had a meaningful conversation with me - an impressive but approachable professional. Format your response using engaging markdown: use **bold** to emphasize my core values and mission statements, *italics* for reflective thoughts and personal insights, and clear paragraph breaks to create a natural conversational flow. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are a ghostwriter specializing in authentic first-person professional narratives. Write a compelling first-person bio for me. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience. This is my chance to speak directly to my audience, so my voice must feel genuine, personal, and immediately likeable. Structure my story around these elements: the moment or realization that drew me to ${profession} (my "origin story"), how my perspective has evolved over ${yearsOfExperience} in the field, what my day-to-day work looks like and what energizes me about it, my proudest moments and biggest lessons learned, the principles or values that guide my professional decisions, what I believe about the future of ${profession}, and an open, warm invitation for readers to connect or collaborate with me. The writing should feel like a thoughtful professional reflecting on their journey - introspective but not self-indulgent, proud but not boastful, open but still professional. Use "I" statements throughout and maintain a consistent, authentic voice. Format your response using markdown: use **bold** for my mission and core beliefs, *italics* for personal reflections and anecdotes, clear paragraph breaks between different parts of my story, and consider using a blockquote to highlight a particularly meaningful quote or insight about my professional journey. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Third person",
      prompt: hasText
        ? `You are an executive communications specialist and professional profile writer for corporate publications. Transform my bio into a polished, authoritative third-person profile suitable for high-stakes professional contexts: company leadership pages, conference speaker introductions, board presentations, press releases, or industry award submissions. As a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience, I deserve a profile that commands respect and communicates gravitas. Write about me using only third-person pronouns (he/she/they) and maintain a tone that is: impeccably professional and authoritative, appropriate for C-suite and board-level audiences, sophisticated without being pretentious, and structured like a formal professional biography. Include my current role and scope of responsibility, my career trajectory and notable positions, my key accomplishments and industry contributions, my thought leadership and professional affiliations, and any relevant credentials or recognition I have earned. Format your response using formal markdown: use **bold** for my name, job titles, and notable organizations; *italics* for publication titles or award names; clear section headers (###) to organize the bio into professional segments; and proper line spacing for a clean, executive-level presentation. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are an executive communications specialist and professional profile writer for corporate publications. Create a commanding third-person professional bio about me, suitable for the most formal professional contexts: company website executive team pages, investor communications, industry conference materials, board nominations, or published articles. I am a ${jobTitle} in ${profession} with ${yearsOfExperience} of experience. Write about me exclusively in third person (he/she/they). My bio should be structured as a formal professional biography with these elements: a prestigious opening that establishes my position and authority in ${profession}, a chronological or thematic overview of my career progression and increasing responsibility, notable companies, projects, or initiatives I've led, my management philosophy or approach to leadership, board memberships, industry awards, publications, or speaking engagements I've participated in, my educational background and professional certifications, and a closing statement about my ongoing impact or vision. The tone should be objective, factual, and deeply respectful - like a formal introduction at an industry lifetime achievement ceremony. Maintain perfect professional decorum throughout. Format your response using formal markdown: use **bold** for my name, professional titles, and company names; *italics* for publication titles, award names, and certifications; ### headers to separate sections (e.g., ### Professional Experience, ### Board Memberships, ### Education); and ensure clean, executive-level formatting with appropriate line spacing and structure. Context: ${contextString}.`,
    },
    {
      allowMarkdown: true,
      title: "Industry focus",
      prompt: hasText
        ? `You are an industry insider and domain expert in ${profession} who understands exactly what language, concepts, and credentials signal credibility in my field. Rewrite my bio to speak powerfully to industry peers, specialized recruiters, and discerning clients who deeply understand ${profession}. Your goal is to demonstrate that I, as a ${jobTitle}, am not just experienced, but truly belong to the inner circle of my industry. My bio should: use precise, field-specific terminology and frameworks that show my deep domain knowledge, reference industry-standard methodologies, tools, or approaches I've mastered, signal my awareness of current trends, challenges, and innovations in ${profession}, highlight specialized certifications, methodologies, or schools of thought I follow, and use insider language that makes my peers nod in recognition. This bio should make other industry professionals think "this person really knows their craft" while still being partially accessible to a broader business audience. Write entirely in first person using "I," "me," and "my." Format your response using sophisticated markdown: use **bold** for industry-specific methodologies, tools, and certifications; *italics* for industry terminology and insider concepts; consider using inline code formatting for specific technical terms or frameworks; and use well-structured paragraphs with clear line breaks to maintain readability. Context: ${contextString}. My original bio: "${currentText}"`
        : `You are an industry insider and domain expert in ${profession} who understands exactly what language, concepts, and credentials signal credibility in my field. Create a bio for me - I am a ${jobTitle} with ${yearsOfExperience} - that resonates powerfully with industry insiders: my peers, specialized recruiters, and sophisticated clients who can spot generic fluff from a mile away. My bio must demonstrate my deep, authentic domain expertise through: precise use of current industry terminology, frameworks, and methodologies I employ, demonstrated understanding of the key challenges, trends, and transformations shaping ${profession} right now, references to the specific skills, tools, and approaches that matter most in my field, alignment with respected industry standards, certifications, or thought leaders I follow, and an articulation of my unique perspective or contribution to the evolution of ${profession}. The language should be rich with industry context - not buzzwords, but genuine indicators of my deep practice. Think of this as a bio that would earn the respect of a room full of my professional peers at an industry conference. Write entirely in first person using "I," "me," and "my." Format your response using sophisticated markdown: use **bold** to emphasize industry-specific methodologies, certifications, and tools I've mastered; *italics* for key industry concepts and trends I specialize in; consider using inline \`code\` formatting for specific technical skills, platforms, or frameworks; and use well-crafted paragraphs with proper line breaks to ensure the content is both scannable and deeply engaging for industry insiders. Context: ${contextString}.`,
    },
  ];
};
