import { PromptOption } from "../ai/AIAsistant";

interface TestimonialContext {
  currentText?: string;
  authorName?: string;
  authorTitle?: string;
  authorCompany?: string;
  authorRelationship?: string; // e.g., "Colleague", "Client", "Manager"
  rating?: number; // 1-5
  recipientUsername?: string; // The person the testimonial is for
}

// Function to generate prompt options with context of existing testimonial
export const getTestimonialPromptOptions = (
  context: TestimonialContext = {},
): PromptOption[] => {
  const {
    currentText = "",
    authorName,
    authorTitle,
    authorCompany,
    authorRelationship,
    rating,
    recipientUsername,
  } = context;

  const hasText = currentText.trim().length > 0;
  const hasContext =
    authorName ||
    authorTitle ||
    authorCompany ||
    authorRelationship ||
    recipientUsername;

  // Return empty array if no proper words/content detected
  if (!hasText && !hasContext) {
    return [];
  }

  // Build context string for prompts
  const buildContextString = () => {
    const parts: string[] = [];
    if (authorName) parts.push(`author: ${authorName}`);
    if (authorTitle) parts.push(`title: ${authorTitle}`);
    if (authorCompany) parts.push(`company: ${authorCompany}`);
    if (authorRelationship) parts.push(`relationship: ${authorRelationship}`);
    if (recipientUsername) parts.push(`for: ${recipientUsername}`);
    if (rating !== undefined) parts.push(`rating: ${rating}/5`);
    return parts.join(", ");
  };

  const contextString = buildContextString();
  const contextPrompt = hasContext ? ` Context: ${contextString}.` : "";

  // Derive relationship-specific context for more targeted prompts
  const relationshipType = authorRelationship?.toLowerCase() || "";
  const isManager =
    relationshipType.includes("manager") ||
    relationshipType.includes("supervisor") ||
    relationshipType.includes("lead");
  const isColleague =
    relationshipType.includes("colleague") ||
    relationshipType.includes("peer") ||
    relationshipType.includes("coworker");
  const isClient =
    relationshipType.includes("client") ||
    relationshipType.includes("customer");
  const isMentee =
    relationshipType.includes("mentee") ||
    relationshipType.includes("report") ||
    relationshipType.includes("direct");

  const relationshipContext = isManager
    ? "As their manager, you have a unique perspective on their growth, leadership potential, and impact on the team."
    : isColleague
      ? "As their colleague, you can speak to their collaboration skills, reliability, and what it's like working alongside them day to day."
      : isClient
        ? "As their client, you can speak to the quality of their deliverables, professionalism, and the value they brought to your project or organization."
        : isMentee
          ? "As someone they've managed or mentored, you can speak to their leadership, guidance, and how they've helped you grow."
          : "";

  return [
    {
      title: "Professional testimonial",
      prompt: hasText
        ? `You are a professional endorsements writer and personal branding specialist who understands that a well-crafted testimonial can be the deciding factor in whether someone gets hired, wins a client, or builds their professional reputation. Rewrite this testimonial to be significantly more polished, impactful, and compelling while preserving the authentic voice and genuine sentiment behind the original. ${authorName ? `You are writing as ${authorName}` : "You are writing as the testimonial author"}, ${authorTitle ? `who holds the position of ${authorTitle}` : "a professional"}${authorCompany ? ` at ${authorCompany}` : ""}${authorRelationship ? `, and your relationship to ${recipientUsername || "the recipient"} is ${authorRelationship}.` : "."} ${relationshipContext} Your revision should: open with a strong, memorable statement that immediately conveys the depth of your endorsement, provide specific, vivid examples of what makes this person exceptional - avoid generic praise like "great to work with" in favor of concrete instances of their excellence, balance professional assessment with personal warmth to create a testimonial that feels both credible and heartfelt,${rating ? ` reflect the high regard indicated by your ${rating}/5 rating, explaining through specific examples why you rate them so highly,` : ""} and close with an unequivocal recommendation that leaves no doubt about your confidence in this person. The testimonial should be substantial enough to carry weight but concise enough to be read in full. Aim for 3-5 well-crafted sentences that together form a powerful, persuasive endorsement. Current testimonial: "${currentText}"`
        : `You are a professional endorsements writer and personal branding specialist who knows that an authentic, well-crafted testimonial can transform a professional profile from merely informative to genuinely persuasive. Write a professional and compelling testimonial${hasContext ? ` for ${contextString}` : ""}. ${authorName ? `You are writing as ${authorName}` : "You are the testimonial author"}, ${authorTitle ? `who holds the position of ${authorTitle}` : "a professional"}${authorCompany ? ` at ${authorCompany}` : ""}${authorRelationship ? `, and your relationship to ${recipientUsername || "the recipient"} is ${authorRelationship}.` : "."} ${relationshipContext} Structure your testimonial to: open with an attention-grabbing endorsement that immediately signals the strength of your recommendation, provide 2-3 specific examples or qualities that make this person stand out - think about what you'd tell a hiring manager if you had 60 seconds to convince them to hire this person, include context about how you worked together and what that revealed about their capabilities and character,${rating ? ` maintain a tone consistent with a ${rating}/5 rating - this level of rating implies ${rating >= 5 ? "exceptional, rare, top-percentile performance" : rating >= 4 ? "strong, above-average performance with notable strengths" : "satisfactory performance with room for growth"},` : ""} and conclude with a clear, confident recommendation that leaves no ambiguity about whether you'd work with them again. Keep the testimonial warm, genuine, and professional - it should feel like it was written by a real person who genuinely believes in this professional, not generated from a template.`,
    },
    {
      title: "Make concise",
      prompt: hasText
        ? `You are a master of impactful brevity who knows that the most powerful endorsements are often the most concentrated. Condense this testimonial into a shorter, punchier version of just 2-3 sentences that maximizes impact per word. Your compression must: identify and preserve the single most powerful piece of praise or most compelling example from the original, eliminate all qualifiers, hedges, and filler that dilute the endorsement's power, compress the remaining content into tight, memorable phrasing that hits hard, ensure the condensed version still feels complete and satisfying - a full endorsement in miniature, and maintain the authentic voice and sentiment of the original author.${authorName ? ` Remember that you are ${authorName},` : ""}${authorRelationship ? ` speaking as a ${authorRelationship} of ${recipientUsername || "the recipient"}.` : "."} The result should be a "mic-drop" testimonial - so tight and powerful that it's more impressive than the longer original. Think of this as the quote that would be pulled out and featured in large text on a website. Current testimonial: "${currentText}"`
        : `You are a master of impactful brevity who can capture the essence of a professional relationship and endorsement in just a few unforgettable sentences. Write a short, punchy testimonial of 2-3 powerful sentences${hasContext ? ` from ${contextString}` : ""} that delivers maximum endorsement impact in minimum space.${authorRelationship ? ` As a ${authorRelationship} of ${recipientUsername || "the recipient"},` : ""} your condensed testimonial should: lead with your strongest praise in the very first phrase - don't build up, come out swinging, include one specific, vivid detail that proves your endorsement is based on real experience, not generic sentiment, use confident, unambiguous language that leaves no room for doubt about your recommendation, and end with a statement that resonates and sticks in the reader's mind. Think of this as the testimonial equivalent of a firm handshake and direct eye contact - brief but absolutely convincing. Every word must earn its place. No sentence should be skippable. The result should feel like a concentrated dose of credibility that makes readers think "if this person thinks so highly of them, they must be exceptional."`,
    },
    {
      title: "Make detailed",
      prompt: hasText
        ? `You are a professional narrative writer who understands that the most compelling testimonials are those rich with specific detail, genuine anecdotes, and textured appreciation. Expand this testimonial into a more detailed, substantive endorsement that provides a complete picture of the working relationship and its value. Your expansion should: add specific examples of projects, situations, or interactions that illustrate the qualities being praised - move from "great problem solver" to "when our product launch was at risk due to a critical bug, they methodically diagnosed and resolved the issue within hours, saving the launch," provide context about the working relationship - how long you worked together, in what capacity, on what types of projects,${authorRelationship ? ` and what made your ${authorRelationship} relationship particularly revealing of their capabilities,` : ""} develop the emotional and professional dimensions of the endorsement - what it felt like to work with them, what you learned from them, how they made a difference beyond just completing tasks,${rating ? ` elaborate on why you give them a ${rating}/5 rating with specific evidence supporting this level of evaluation,` : ""} and create a narrative arc that takes the reader from the context of your relationship through specific evidence of excellence to a powerful concluding recommendation. Keep the expanded testimonial under 2000 characters while making every sentence contribute meaningful detail. The result should read like a thoughtful, unhurried reflection from someone who truly knows and values this professional's work. Current testimonial: "${currentText}"`
        : `You are a professional narrative writer who believes that the best testimonials are mini-portraits of professional excellence painted through specific, vivid detail. Generate a detailed, substantive testimonial${hasContext ? ` for ${contextString}` : ""}.${authorName ? ` You are ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""}${authorRelationship ? ` writing as a ${authorRelationship} of ${recipientUsername || "the recipient"}.` : "."} ${relationshipContext} Your detailed testimonial should include: the context and duration of your working relationship - how you came to work together and what the professional dynamic was like, 2-3 specific stories or examples that illustrate their capabilities in action - concrete situations where they demonstrated excellence, problem-solving, leadership, or growth, observations about their work style, professional character, and what makes them distinctive - go beyond skills to describe the person behind the work, the impact they had on projects, teams, or outcomes - what would have been different or lost without their contribution,${rating ? ` specific justification for your ${rating}/5 rating, explaining what excellence at this level looks like and how they demonstrated it,` : ""} and a forward-looking recommendation that speaks to their potential and the value they would bring to future opportunities. Keep it under 2000 characters while being generous with meaningful detail. The testimonial should feel like a comprehensive, thoughtful endorsement that leaves readers with a three-dimensional understanding of this professional's excellence.`,
    },
    {
      title: "Results focused",
      prompt: hasText
        ? `You are a business impact analyst and testimonial strategist who knows that the most persuasive endorsements connect personal qualities to measurable outcomes. Rewrite this testimonial to emphasize the tangible results, measurable impact, and specific outcomes that ${recipientUsername || "the recipient"} achieved while working with you${authorRelationship ? ` as their ${authorRelationship}` : ""}. Your revision should answer the critical question every reader has: "What did this person actually accomplish?" Shift the testimonial from describing admirable qualities to demonstrating proven impact. For each strength or quality mentioned, connect it to a concrete result: not "great communicator" but "their communication with stakeholders kept a $2M project on track and resulted in zero misalignment issues," not "hard worker" but "their commitment during the final weeks of the project directly enabled us to meet an immovable regulatory deadline."${rating ? ` Your ${rating}/5 rating should be backed by results that justify this level of evaluation.` : ""} Use specific metrics where possible (percentages, dollar amounts, time saved, team sizes, project values). Where exact numbers aren't available, use descriptive but concrete language about the scale and significance of their contributions. The result should be a testimonial that reads like a mini performance review focused exclusively on verifiable impact. Current testimonial: "${currentText}"`
        : `You are a business impact analyst and testimonial strategist who believes that the most powerful endorsements are those that prove value through concrete results. Generate a results-focused testimonial${hasContext ? ` for ${contextString}` : ""} that emphasizes measurable outcomes, tangible contributions, and specific improvements driven by ${recipientUsername || "the recipient"}.${authorRelationship ? ` As their ${authorRelationship},` : ""}${authorName ? ` you as ${authorName}` : " you"} are uniquely positioned to speak to the concrete impact they delivered. Structure your testimonial around 2-3 specific results or outcomes, each following a clear pattern: the situation or challenge that existed, the specific actions they took or contributions they made, and the measurable result or impact that followed. Consider different dimensions of results: financial impact (revenue generated, costs reduced, budget optimized), operational impact (efficiency improved, time saved, processes streamlined), quality impact (error reduction, satisfaction improvements, compliance achieved), team impact (productivity gains, morale improvements, capability building), and client/customer impact (satisfaction scores, retention improvements, relationship strengthening).${rating ? ` The results described should be consistent with and justify a ${rating}/5 rating.` : ""} The testimonial should read like compelling evidence of someone who doesn't just do good work, but delivers measurable value. Quantify wherever possible; be specifically descriptive where exact numbers aren't available.`,
    },
    {
      title: "Story-driven",
      prompt: hasText
        ? `You are a professional storyteller and narrative strategist who knows that human beings are wired to remember stories, not lists of qualities. Transform this testimonial into a compelling mini-story with a clear narrative arc that makes the endorsement memorable, relatable, and emotionally resonant. Structure your story-driven testimonial around this proven framework: **The Beginning** - Set the scene. How did your working relationship with ${recipientUsername || "the recipient"} begin? What was the context, the project, the challenge, or the initial impression? Create a vivid opening that draws the reader in. **The Middle** - Describe the journey. What was the challenge, project, or period of working together like? What specific moments, interactions, or turning points revealed their character and capabilities? Build tension or interest by showing what was at stake. **The Result** - Deliver the satisfying conclusion. What was the outcome? How did their contribution make a difference? What did you learn or gain from the experience? What would you want others to know? ${authorRelationship ? `As their ${authorRelationship},` : ""}${authorName ? ` ${authorName},` : ""} your perspective adds unique weight to this story. The testimonial should read like a brief but vivid account that makes the reader feel they were there, witnessing this professional's excellence firsthand. Current testimonial: "${currentText}"`
        : `You are a professional storyteller and narrative strategist who understands that a well-told story is remembered long after a list of adjectives is forgotten. Create a story-driven testimonial${hasContext ? ` for ${contextString}` : ""} that follows a compelling narrative arc and makes the endorsement come alive through storytelling.${authorName ? ` You are ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""}${authorRelationship ? ` writing as a ${authorRelationship} of ${recipientUsername || "the recipient"}.` : "."} ${relationshipContext} Structure your testimonial as a three-part narrative: **Act I - The Context** - Paint the scene vividly. Describe the project, challenge, or professional situation where you worked together. What was at stake? What was the environment? What initial impressions did you form? Make the reader understand why this situation mattered. **Act II - The Journey** - Bring the working relationship to life through specific moments. Describe key interactions, challenges faced together, or instances where ${recipientUsername || "they"} demonstrated exceptional qualities. Use sensory and emotional detail - what was it actually like? What surprised you? What made you think "this person is different"? **Act III - The Resolution** - Describe the outcome and its significance. What was achieved? How did the story end? More importantly, what did this experience reveal about their character and capabilities that a simple list of skills could never convey? The testimonial should engage the reader as a story does - making them want to know what happens next - while serving as a powerful professional endorsement. Keep it concise enough to read in under a minute while being vivid enough to remember.`,
    },
    {
      title: "Casual & authentic",
      prompt: hasText
        ? `You are an authenticity coach and conversational copywriter who knows that the most trusted testimonials sound like a real person talking, not a corporate endorsement. Rewrite this testimonial in a warm, casual, conversational tone that feels like a genuine word-of-mouth recommendation shared over coffee. Your rewrite should: strip away any formal, corporate, or templated language that makes the testimonial feel manufactured, adopt the natural speech patterns of ${authorName || "a real person"} - use contractions, varied sentence lengths, and occasional colloquialisms that feel authentic, sound like someone genuinely enthusiastic about recommending a colleague they respect - let the warmth and sincerity come through, maintain professionalism not through formal language but through the substance and specificity of the praise, and include small, human details that only someone who actually worked with ${recipientUsername || "this person"} would know - the kind of observations that prove this is a real endorsement from real experience.${authorRelationship ? ` As a ${authorRelationship},` : ""} your voice should reflect the unique perspective your relationship provides. The result should feel like you're overhearing someone give an unprompted, heartfelt recommendation - not reading a prepared statement. Current testimonial: "${currentText}"`
        : `You are an authenticity coach and conversational copywriter who believes that the most powerful testimonials sound less like formal endorsements and more like someone you trust telling you about someone they respect. Generate a casual, authentic testimonial${hasContext ? ` for ${contextString}` : ""} that reads like genuine word-of-mouth praise.${authorName ? ` Write as ${authorName},` : ""}${authorRelationship ? ` a ${authorRelationship} of ${recipientUsername || "the recipient"},` : ""} using your natural voice.${authorTitle ? ` As ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""} you have professional credibility, but your tone should be warm and human, not corporate. Your testimonial should: open the way a real person starts a recommendation - maybe with a direct statement like "I've worked with a lot of people, and honestly..." or "If you're thinking about working with..., here's what you should know...," include specific but casually-delivered observations that feel like insights from real experience, not bullet points from a review form, sound like you're having a conversation with someone who asked "what are they like to work with?" - natural, unrehearsed, genuine,${rating ? ` subtly reflect your ${rating}/5 rating through the enthusiasm and conviction of your language rather than explicitly stating a score,` : ""} and end with a natural conclusion - maybe a statement of confidence, a wish to work together again, or simple, direct endorsement. The testimonial should feel so authentic that readers trust it immediately because it sounds like a real person sharing a real opinion, not a polished PR statement.`,
    },
    {
      title: "LinkedIn recommendation",
      prompt: hasText
        ? `You are a LinkedIn profile optimization expert and professional networking specialist who understands the specific conventions and expectations of LinkedIn recommendations. Reformat this testimonial as a polished, platform-appropriate LinkedIn recommendation that will enhance ${recipientUsername || "the recipient"}'s professional profile. A strong LinkedIn recommendation should: begin by clearly establishing your professional relationship - how you know each other, in what capacity you worked together, and for how long${authorRelationship ? ` (as their ${authorRelationship}),` : ","} provide specific, credible examples of their work and impact - LinkedIn readers are skeptical of vague praise and respond to evidence, highlight skills and qualities that are relevant to their career goals and the opportunities they're pursuing, balance professional assessment with personal endorsement - LinkedIn recommendations work best when they're both credible and warm, and include a clear, confident recommendation statement.${authorName ? ` Write as ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany}.` : "."} ${rating ? ` Your ${rating}/5 rating should be communicated through the strength of your endorsement rather than stated numerically.` : ""} The recommendation should be substantial enough to be meaningful (LinkedIn's minimum is character-based, but quality recommendations are 3-5 sentences) while being scannable for busy recruiters. Current testimonial: "${currentText}"`
        : `You are a LinkedIn profile optimization expert and professional networking specialist who has reviewed thousands of LinkedIn recommendations and knows exactly what makes some compelling and others forgettable. Write a polished, professional LinkedIn recommendation${hasContext ? ` for ${contextString}` : ""}.${authorName ? ` Write as ${authorName},` : ""}${authorTitle ? ` who is ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany}.` : "."}${authorRelationship ? ` Your relationship to ${recipientUsername || "the recipient"} is ${authorRelationship}.` : ""} ${relationshipContext} Structure the recommendation following LinkedIn best practices: **Opening** - Clearly state your professional relationship. How do you know this person? In what capacity did you work together? For how long? This establishes your credibility as a recommender immediately. **Body** - Provide 2-3 specific, compelling points about their work. Focus on: what they did that was exceptional (with examples), the skills and qualities they demonstrated (be specific - not "good communicator" but "their ability to translate complex technical concepts for executive stakeholders"), how they impacted the team, project, or organization, and what distinguishes them from other professionals you've worked with. **Closing** - Deliver a clear, confident recommendation. State unequivocally that you recommend them and, if appropriate, the types of roles or opportunities they're well-suited for.${rating ? ` The recommendation should convey the enthusiasm of a ${rating}/5 rating through language rather than stating the number.` : ""} The tone should be professional yet personal - credible enough for recruiters and hiring managers, warm enough to feel genuine. Keep it concise but substantial (3-5 well-crafted sentences). This recommendation will live on their LinkedIn profile, so it should be something they're proud to display.`,
    },
    {
      title: "Highlight skills",
      prompt: hasText
        ? `You are a talent assessment specialist and skills-based endorsement expert who knows that the most useful testimonials are those that provide specific, credible evidence of professional capabilities. Enhance this testimonial to explicitly and vividly highlight the key skills, strengths, and qualities that ${recipientUsername || "the recipient"} demonstrated while working with you${authorRelationship ? ` as their ${authorRelationship}` : ""}. Your enhancement should: identify 3-4 specific skills or strengths demonstrated through your working relationship, for each skill, provide a concrete example or instance that proves their capability - not "skilled at project management" but "managed a complex, cross-functional project with 15 stakeholders across 4 time zones, delivering on time and under budget," connect skills to outcomes - show how each capability translated into tangible value or results, distinguish between technical skills (tools, methodologies, domain expertise) and professional skills (leadership, communication, problem-solving, collaboration), and create a balanced portrait that shows both depth of expertise and breadth of capability.${authorName ? ` As ${authorName},` : ""} your professional standing${authorTitle ? ` as ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany}` : ""} lends weight to your assessment of their capabilities. The result should read like a thoughtful, evidence-based evaluation that would help a hiring manager understand exactly what this person brings to the table. Current testimonial: "${currentText}"`
        : `You are a talent assessment specialist and skills-based endorsement expert who understands that generic praise is forgettable, but specific skill validation is invaluable. Generate a testimonial${hasContext ? ` for ${contextString}` : ""} that highlights specific skills, strengths, and professional qualities demonstrated by ${recipientUsername || "the recipient"}.${authorName ? ` As ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""}${authorRelationship ? ` and their ${authorRelationship},` : ""} you have direct knowledge of their capabilities. ${relationshipContext} Structure your testimonial to serve as a comprehensive skills validation: identify 3-4 key skills or strengths you've observed firsthand, for each skill provide: a specific example or situation where you saw it demonstrated, the level of proficiency or sophistication at which they operate, and the impact or outcome their application of this skill produced. Cover different categories of professional capability: technical/functional skills specific to their domain, interpersonal and collaboration skills, problem-solving and analytical abilities, leadership and initiative qualities (regardless of formal title), and work ethic and professional character attributes.${rating ? ` The skills described should reflect and justify a ${rating}/5 level of performance.` : ""} The testimonial should read like a curated portfolio of their professional capabilities - each skill backed by evidence, each claim supported by your direct observation. This approach transforms a testimonial from "nice things someone said" into "credible evidence of professional capability."`,
    },
    {
      title: "Leadership praise",
      prompt: hasText
        ? `You are an executive coach and leadership assessment specialist who knows how to identify and articulate the leadership qualities that distinguish exceptional professionals. Rewrite this testimonial to powerfully emphasize the leadership qualities, team impact, and ability to inspire, guide, and elevate others that ${recipientUsername || "the recipient"} demonstrated${authorRelationship ? ` in their role as your ${authorRelationship}` : ""}. Your revision should highlight leadership in all its forms - not just formal management, but the ability to influence, inspire, take ownership, drive results through others, and elevate the performance of everyone around them. Specifically address: **Strategic Vision** - How did they see the bigger picture and guide work accordingly? **Team Development** - How did they help others grow, improve, or succeed? What was their impact on team morale, culture, or capability? **Initiative & Ownership** - How did they take responsibility beyond their formal role? What problems did they solve without being asked? **Influence & Communication** - How did they bring people along, build consensus, or communicate in ways that moved work forward? **Resilience & Composure** - How did they handle pressure, setbacks, or difficult situations in ways that steadied and inspired others?${authorName ? ` As ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""} your perspective carries weight, especially regarding their leadership qualities. The result should position ${recipientUsername || "them"} as someone who leads regardless of title - a professional others want to follow and organizations are lucky to have. Current testimonial: "${currentText}"`
        : `You are an executive coach and leadership assessment specialist who understands that leadership is demonstrated through influence and impact, not job titles. Generate a testimonial${hasContext ? ` for ${contextString}` : ""} that focuses specifically on leadership qualities, team impact, and the ability to inspire and elevate others.${authorName ? ` Write as ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""}${authorRelationship ? ` speaking as a ${authorRelationship} of ${recipientUsername || "the recipient"}.` : "."} ${relationshipContext}${isManager || isMentee ? " Your perspective as someone who has seen their leadership directly is particularly valuable." : " Even as a " + (authorRelationship || "colleague") + ", you can speak to how they lead through influence, example, and initiative."} Structure the testimonial around dimensions of leadership: **Vision & Strategic Thinking** - Describe how they see beyond immediate tasks to understand bigger-picture implications and guide work accordingly, **Team Impact & Development** - Detail how they elevate those around them through mentoring, knowledge sharing, support, or simply setting a standard of excellence that inspires others, **Initiative & Ownership** - Provide examples of how they step up, take responsibility, solve problems proactively, and demonstrate the accountability that defines true leaders, **Communication & Influence** - Show how they bring people together, facilitate collaboration, navigate difficult conversations, or communicate in ways that create clarity and momentum, and **Character & Composure** - Speak to the personal qualities that make them someone others trust and want to follow - integrity, consistency, grace under pressure, genuine care for outcomes and people.${rating ? ` Your ${rating}/5 rating should be reflected in the strength of your endorsement of their leadership capabilities.` : ""} The testimonial should position ${recipientUsername || "them"} as a natural leader - the kind of professional who elevates every team they're on, regardless of their formal title or position in the hierarchy.`,
    },
    {
      title: "Diverse angles",
      prompt: hasText
        ? `You are a multi-perspective endorsement strategist who understands that different audiences care about different aspects of a professional's capabilities. Generate 3 distinct variations of this testimonial, each crafted to emphasize a different dimension of ${recipientUsername || "the recipient"}'s professional excellence. Each variation should feel like a complete, standalone testimonial while highlighting a different facet of their value. **Variation 1 - Work Quality & Expertise**: Focus on the caliber of their work, technical or professional expertise, attention to detail, and the quality standards they maintain. What makes their output exceptional? What would suffer without their standards? **Variation 2 - Collaboration & Teamwork**: Focus on what it's like to work with them day to day. Their communication style, reliability, how they handle feedback, their contribution to team culture and morale. What makes them someone others want on their team? **Variation 3 - Reliability & Professionalism**: Focus on their consistency, dependability, professional integrity, and the trust they build. Can you count on them when it matters? Do they deliver on commitments? How do they conduct themselves professionally?${authorName ? ` As ${authorName},` : ""}${authorRelationship ? ` their ${authorRelationship},` : ""} your voice should remain consistent across all three variations while the emphasis shifts. Each variation should be 2-4 sentences and read as a complete, polished testimonial in its own right. Current testimonial: "${currentText}"`
        : `You are a multi-perspective endorsement strategist who understands that different stakeholders evaluate professionals through different lenses. Generate 3 distinct testimonial variations${hasContext ? ` for ${contextString}` : ""}, each written from a different angle to showcase different dimensions of ${recipientUsername || "the recipient"}'s professional excellence.${authorName ? ` All are written as ${authorName},` : ""}${authorTitle ? ` ${authorTitle}` : ""}${authorCompany ? ` at ${authorCompany},` : ""}${authorRelationship ? ` a ${authorRelationship} of ${recipientUsername || "the recipient"}.` : "."} ${relationshipContext} Each variation should be a complete, polished testimonial of 2-4 sentences with a distinct focus: **Variation 1 - Work Quality & Technical Excellence**: Focus on the caliber of their deliverables, their expertise and mastery of their craft, their attention to detail, and the quality standards they uphold. What makes their work product exceptional? What would be lost without their quality standards? This variation speaks to those evaluating technical or professional competence. **Variation 2 - Collaboration & Interpersonal Impact**: Focus on what it's like to work alongside them. Their communication approach, how they handle feedback and conflict, their contribution to team dynamics and morale, and their reliability as a teammate. What makes them someone others actively want to work with? This variation speaks to those evaluating culture fit and team compatibility. **Variation 3 - Professional Character & Reliability**: Focus on their integrity, consistency, trustworthiness, and professional conduct. Do they deliver on commitments? Can they be counted on in high-stakes situations? How do they conduct themselves under pressure? This variation speaks to those evaluating character and dependability. Each variation should stand alone as a complete endorsement while collectively painting a three-dimensional portrait of a well-rounded professional. Label each variation clearly with its angle focus.`,
    },
  ];
};
