import { PromptOption } from "../ai/AIAsistant";

interface ExperienceFormData {
  job_title: string;
  company_name: string;
  employment_type?: string;
  location_type?: string;
  location?: string;
  start_date: string;
  end_date?: string;
  is_current: boolean;
  description?: string;
  industry?: string;
  company_size?: string;
  skills_used?: string;
  responsibilities?: string;
}

// Function to generate prompt options for experience description
export const getExperienceDescriptionPromptOptions = (
  formData: ExperienceFormData,
  currentText: string,
): PromptOption[] => {
  const { job_title, company_name, start_date } = formData;

  // Return empty array if required fields are missing
  if (!job_title?.trim() || !company_name?.trim() || !start_date?.trim()) {
    return [];
  }

  const hasText = currentText.trim().length > 0;
  const company = company_name.trim();
  const title = job_title.trim();
  const employmentType = formData.employment_type || "full-time";
  const locationType = formData.location_type || "on-site";
  const location = formData.location?.trim();
  const industry = formData.industry?.trim();
  const companySize = formData.company_size?.trim();
  const skillsUsed = formData.skills_used?.trim();
  const dateRange = formData.is_current
    ? `since ${start_date}`
    : `from ${start_date} to ${formData.end_date || "present"}`;

  // Build context-rich description
  const roleContext = [
    employmentType,
    locationType,
    location ? `in ${location}` : "",
    industry ? `in the ${industry} industry` : "",
    companySize ? `at a ${companySize.toLowerCase()} company` : "",
  ]
    .filter(Boolean)
    .join(", ");

  const skillsContext = skillsUsed ? ` Key skills include: ${skillsUsed}.` : "";

  return [
    {
      title: "Improve description",
      prompt: hasText
        ? `You are an executive resume writer and career coach who has crafted thousands of job descriptions that have helped professionals land interviews at top companies. Rewrite this job description for a ${title} at ${company} to be dramatically more impactful, compelling, and achievement-oriented. This role is ${roleContext}${skillsContext}, and your revision should transform it from a list of duties into a powerful narrative of professional contribution and demonstrated value. Your approach: lead with the most impressive aspect of the role - scope, impact, or unique responsibility, use dynamic action verbs that convey leadership, initiative, and ownership (avoid passive constructions like "responsible for" or "duties included"), quantify scope and impact wherever possible - team sizes, budgets managed, revenue influenced, users served, projects led, efficiency gains achieved, connect daily responsibilities to broader business outcomes to show strategic awareness, and maintain a confident, professional tone that positions this person as a high-performer who delivers results. The description should make recruiters and hiring managers think "this person made a real difference here" rather than "this person showed up and did their job." Current description: "${currentText}"`
        : `You are an executive resume writer and career coach who specializes in crafting job descriptions that differentiate candidates in competitive markets. Write a compelling, detailed job description for a ${title} at ${company}. This role is ${roleContext}${skillsContext}, and your description needs to establish immediate credibility and demonstrate the substance of this professional experience. Structure it as 3-4 powerful sentences that: open by establishing the role's primary mission and scope - what was this person entrusted with and what did success look like?, describe 2-3 key areas of responsibility using vivid, action-oriented language that shows not just what was done but the sophistication and impact of how it was done, incorporate relevant context about the environment (${companySize ? `${companySize} company` : "organization"}, ${industry ? `${industry} industry` : "the industry"}) to help readers understand the setting and stakes, and close with the overarching impact or value this person brought to the organization. Use strong verbs like "spearheaded," "orchestrated," "transformed," "architected," "drove," and "championed." Avoid generic filler; every sentence should add meaningful information that helps a future employer understand capability and potential.`,
    },
    {
      title: "Industry-specific",
      prompt: hasText
        ? `You are an industry specialist and domain expert${industry ? ` with deep knowledge of the ${industry} sector` : ""} who understands the specific language, expectations, and value signals that matter in this field. Rewrite this description for a ${title} at ${company} (${roleContext}) to resonate powerfully with industry insiders. Your revision should: incorporate precise, field-specific terminology, frameworks, and concepts that demonstrate genuine domain fluency, reference industry-standard practices, regulations, or methodologies that signal someone who deeply understands this space, use language and achievement framing that would impress a senior leader in ${industry || "this field"} - the kind of person who can spot generic fluff from a mile away, highlight domain-specific challenges overcome and industry-relevant outcomes achieved, and position the experience within the broader context of ${industry || "the industry"} trends, challenges, or evolution. The revised description should sound like it was written by someone who doesn't just work in the industry, but truly understands its nuances, challenges, and what excellence looks like. Current description: "${currentText}"`
        : `You are an industry specialist and domain expert who knows that the most compelling job descriptions speak the language of their field fluently. Write an industry-focused description for a ${title} at ${company} (${roleContext}). Your description must demonstrate authentic domain expertise through: precise use of industry terminology, frameworks, and concepts that signal deep familiarity with the field, references to industry-specific challenges, trends, regulations, or best practices that show contextual awareness, description of work in terms that would resonate with and impress industry peers and leaders, connection of the role's contributions to broader industry impact or advancement, and subtle demonstration of understanding the competitive landscape, key players, and where ${company} fits in the industry ecosystem. The description should position this professional as someone who has not just worked in the industry, but has developed genuine expertise and perspective that would be valuable to any organization in this space. Avoid generic business language that could apply to any industry; make it unmistakably clear what domain this expertise lives in.`,
    },
    {
      title: "Skills highlight",
      prompt: hasText
        ? `You are a talent development specialist and skills strategist who understands that the best job descriptions don't just list skills - they demonstrate skills through evidence of application and impact. Enhance this description for a ${title} at ${company} by weaving ${skillsUsed || "the relevant technical and professional competencies"} into the narrative in a way that shows how each capability was applied to create tangible value. Your approach: for each skill mentioned, follow it with evidence of application - not "used Python" but "leveraged Python to build data pipelines that processed 10M+ records daily," not "strong communicator" but "facilitated executive presentations that secured $2M in project funding," demonstrate the sophistication level of skill application - show whether skills were used for routine tasks or complex challenges, highlight unique combinations of skills that created distinctive value - the intersection of technical and business skills, for example, and show skill progression and deepening over the course of the role. The result should read as a compelling record of capability demonstrated through action, not a list of claimed competencies. Current description: "${currentText}"`
        : `You are a talent development specialist and skills strategist who believes that skills are best proven through the results they produce. Write a skills-focused description for a ${title} at ${company} (${roleContext}) that demonstrates how specific competencies drove meaningful outcomes. Structure the description to show: the primary skills that defined success in this role (both technical and professional), how each key skill was applied in practice - move beyond "skilled in X" to "applied X to achieve Y," the level of sophistication at which skills were exercised (basic application vs. advanced problem-solving vs. innovative application vs. teaching/mentoring others), specific examples of skills translating into business or organizational impact, and the unique combination or intersection of skills that made this professional particularly effective in this role. The description should make a compelling case that this person doesn't just possess skills on paper - they know how to deploy them effectively to create value. This approach is far more convincing than simply listing competencies because it provides evidence, not just claims.`,
    },
    {
      title: "Make concise",
      prompt: hasText
        ? `You are a master of professional communication who can compress a complex career narrative into its most potent, memorable form. Condense this job description for ${title} at ${company} into just 2-3 extraordinarily powerful sentences that capture the absolute essence and impact of this role. Your compression must: identify and retain only the most differentiating and impressive aspects of the experience, eliminate all redundancy, filler, context that's nice-to-have but not essential, and passive or weak constructions, compress complex responsibilities and achievements into tight, punchy phrasing that maximizes impact-per-word, ensure the condensed version still communicates scope, capability level, and primary impact, and create a version so tight and powerful that it functions as a verbal highlight reel - the 30-second version that makes someone say "tell me more." Context: ${roleContext}${skillsContext}. Current text: "${currentText}"`
        : `You are a master of professional brevity who knows that sometimes the most powerful resume bullets are the shortest. Create a razor-sharp 2-sentence summary for a ${title} at ${company} (${roleContext}) that communicates more in two sentences than most descriptions do in a paragraph. Sentence one should establish: the role's primary mission, the scope or scale of responsibility, and the core capability demonstrated. Sentence two should communicate: the most significant impact or achievement, the value delivered to the organization, and a hint of what makes this experience distinctive. Every word must earn its place. Use concrete, specific language that creates a clear picture. Avoid: "responsible for," "helped with," "participated in," "assisted," and any other weak verbs that undersell contribution. Think of this as the description that would appear under this job title in a "Top Professionals in ${industry || "the Industry"}" feature - it needs to command attention and convey substance instantly. The result should feel dense with meaning, not thin with generalities.`,
    },
    {
      title: "Add metrics",
      prompt: hasText
        ? `You are a data-driven resume strategist who knows that quantified achievements are the single most powerful element in any job description. Enhance this description for a ${title} at ${company} by strategically incorporating relevant, believable metrics that prove the scale and impact of the work. Go beyond vague success claims and ground the narrative in numbers that make the contribution tangible. Consider metrics across multiple dimensions: scope metrics (team size led, budget managed, users/clients served, projects overseen, markets covered), performance metrics (revenue growth, cost reduction, efficiency improvements, productivity gains, cycle time reduction), scale metrics (data processed, transactions handled, systems maintained, products shipped), quality metrics (error reduction, satisfaction scores, compliance achievement, retention rates), and growth metrics (team growth, revenue trajectory, market share expansion, user acquisition). Integrate metrics naturally - they should enhance the story, not feel bolted on. Each metric should serve to prove a specific claim about the role's impact. Use specific numbers where available; use well-reasoned estimates where exact figures aren't known. Context: ${roleContext}${skillsContext}. Current text: "${currentText}"`
        : `You are a data-driven resume strategist who has studied what makes hiring managers and recruiters stop and take notice - and the answer is almost always numbers. Write a metrics-driven description for a ${title} at ${company} (${roleContext}) where quantifiable scope and impact are woven throughout the narrative. Your description should establish the scale of the role through specific numbers: how many people, how much money, how many users, how many projects, what size organization, what growth trajectory. Then demonstrate impact through measurable outcomes: what improved, by how much, over what timeframe. Consider these metric categories for ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"}${industry ? ` in ${industry}` : ""}: operational metrics (efficiency gains, time savings, automation rates, error reduction), financial metrics (revenue impact, cost savings, budget optimization, ROI achieved), people metrics (team size and growth, retention, engagement, promotion rates), customer metrics (satisfaction scores, NPS, retention rates, growth metrics), and delivery metrics (projects completed, on-time delivery rates, quality scores).${skillsUsed ? ` For skills like ${skillsUsed}, consider what metrics would naturally demonstrate proficiency and impact.` : ""} The description should leave readers with a clear, quantified understanding of the scale at which this professional operates and the tangible value they deliver.`,
    },
    {
      title: "Leadership focus",
      prompt: hasText
        ? `You are an executive career coach who specializes in positioning professionals for leadership roles. Rewrite this description for a ${title} at ${company} to powerfully emphasize leadership capabilities, strategic influence, and organizational impact. This role at ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"}${industry ? ` in ${industry}` : ""} should be framed as a leadership experience, regardless of whether it was a formal management position. Your revision should highlight: strategic thinking and decision-making - how did this person shape direction, not just execute tasks?, influence and cross-functional leadership - how did they lead through influence, collaboration, and relationship-building even without direct authority?, team development and mentoring - how did they elevate others and contribute to organizational capability?, change management and transformation - what improvements, turnarounds, or innovations did they drive?, and vision and communication - how did they align stakeholders, present to leadership, or advocate for important initiatives?. Use leadership language: "set the vision for," "built consensus around," "championed," "influenced strategy," "developed talent," "drove organizational change." The description should position this person as someone who thinks and acts like a leader, not just an individual contributor executing tasks. Current description: "${currentText}"`
        : `You are an executive career coach who understands that leadership is demonstrated through influence and impact, not just titles. Write a leadership-focused description for a ${title} at ${company} (${roleContext}) that showcases the strategic and organizational leadership dimensions of this role. Structure the description to demonstrate leadership through: strategic contribution - how this person shaped goals, influenced direction, identified opportunities, or drove important decisions, organizational impact - how their work affected the broader organization beyond their immediate responsibilities, team and talent development - formal or informal mentoring, knowledge sharing, onboarding, or capability building they contributed to, cross-functional influence - how they collaborated across teams, built alignment, or broke down silos to achieve outcomes, thought leadership - how they contributed ideas, best practices, or innovations that elevated the organization's capabilities, and change agency - improvements they drove, problems they identified and solved, or transformations they led. Even if this wasn't a formal management role, frame it in terms of the leadership behaviors demonstrated. Use language that positions this person as someone who takes ownership beyond their job description, sees the bigger picture, and elevates those around them. This approach is particularly effective for ${companySize ? `a ${companySize.toLowerCase()} company` : "organizations"} where leadership can be demonstrated at any level.`,
    },
    {
      title: "Technical focus",
      prompt: hasText
        ? `You are a technical recruiter and engineering manager who knows exactly what signals technical competence in a job description. Reframe this description for a ${title} at ${company}${industry ? ` in the ${industry} industry` : ""} to spotlight technical skills, tools, methodologies, and engineering practices with precision and depth. Your revision should: name specific technologies, versions, frameworks, and tools with the confidence of someone who has hands-on experience, describe technical work in terms of architecture, design decisions, and implementation approaches rather than just listing technologies, demonstrate understanding of technical trade-offs, best practices, and engineering principles, show the scale and complexity of technical challenges tackled (system scale, data volumes, performance requirements, integration complexity), and highlight any technical leadership, innovation, or particularly sophisticated problem-solving.${skillsUsed ? ` Incorporate ${skillsUsed} in a way that shows genuine proficiency, not just familiarity.` : ""} The description should read like it was written by someone who truly understands the technology - using terms naturally and precisely, not like someone who added keywords from a job posting. Current text: "${currentText}"`
        : `You are a technical recruiter and engineering manager who can distinguish between candidates who have worked with technologies and those who truly understand them. Write a technically-focused description for a ${title} at ${company} (${roleContext}) that demonstrates genuine technical depth. Your description should communicate: the specific technologies, tools, platforms, and methodologies used - be precise about versions, ecosystems, and technical context, the nature and sophistication of technical work performed - architecture, design, development, optimization, integration, or innovation, the technical challenges faced and how they were solved - this demonstrates problem-solving ability, not just tool usage, the scale and complexity of technical systems worked on (user base, data volume, system requirements, performance constraints), engineering practices and standards applied - testing, CI/CD, code review, documentation, technical decision-making, and any technical mentorship, leadership, or community contribution.${skillsUsed ? ` With skills in ${skillsUsed}, describe how these were applied at an advanced level, not just utilized at a basic level.` : ""} The description should satisfy both technical readers (who will appreciate precise, accurate technical language) and non-technical readers (who will understand that this person has serious technical credibility). Avoid technology buzzword bingo; every technical term should connect to genuine hands-on work.`,
    },
    {
      title: "Career progression",
      prompt: hasText
        ? `You are a career narrative specialist who knows that the most compelling professional stories show growth, not just a static set of responsibilities. Transform this description for a ${title} at ${company} (${roleContext}) into a narrative of professional development and increasing impact. Show the arc of growth over this period ${dateRange}: how did responsibilities expand? How did capabilities deepen? What did this person grow into? Your revision should: establish the starting point - what was the initial scope, challenge, or mandate when joining/starting this role?, show progression milestones - promotions, expanded responsibilities, increasingly complex projects, growing autonomy, describe how capabilities evolved - new skills acquired, deeper expertise developed, leadership abilities emerged, highlight the learning trajectory - what was challenging at first that became second nature? What new domains were conquered?, and conclude with the current state - what level of mastery, responsibility, and impact has been achieved?${skillsUsed ? ` Show specifically how skills like ${skillsUsed} developed from foundational to advanced application.` : ""} The description should read like a story of someone who doesn't just occupy a role, but grows within it, making themselves increasingly valuable over time. Current text: "${currentText}"`
        : `You are a career narrative specialist who believes that a job description should tell a story of growth, not just list a snapshot of responsibilities. Create a description that shows career progression for a ${title} at ${company} over the period ${dateRange} (${roleContext}). Structure this as a narrative of professional evolution: begin with the initial context - what was the situation when this person started? What was the mandate, the team, the challenges? Describe how the role evolved - expanded scope, increased complexity, new responsibilities taken on, promotions or title changes if applicable, show capability growth - skills deepened, new competencies developed, leadership emerged, autonomy increased, highlight key moments or projects that marked growth inflection points - the challenging assignment that accelerated development, the initiative that expanded influence, the crisis that proved capability, and convey the current level - what is this person now capable of that they weren't at the start? How has their professional identity and value evolved? The description should demonstrate that this professional doesn't just have experience - they have a track record of growth and increasing contribution. This signals to future employers that they'll continue to grow and take on more in their next role.`,
    },
    {
      title: "ATS optimization",
      prompt: hasText
        ? `You are an ATS (Applicant Tracking System) optimization specialist and recruitment technology expert who understands exactly how automated systems parse, analyze, and rank job descriptions. Optimize this description for a ${title} at ${company} for maximum ATS performance while keeping it completely natural and compelling for human readers. Your optimization strategy: identify and naturally incorporate the most important keywords and phrases that ATS systems associate with ${title} roles${industry ? ` in ${industry}` : ""}, include semantic variations and related terms that broaden keyword coverage without stuffing, align language with standard industry job taxonomies and classification frameworks used by major ATS platforms, incorporate relevant tools, methodologies, certifications, and qualifications as natural search triggers, maintain keyword density that optimizes for search relevance without appearing spammy or manipulated, and ensure the optimized text reads naturally - modern ATS systems and certainly human recruiters penalize obvious keyword stuffing. Context: ${roleContext}${skillsContext}. Current text: "${currentText}"`
        : `You are an ATS (Applicant Tracking System) optimization specialist who understands the algorithms, parsing logic, and keyword matching systems used by platforms like Workday, Greenhouse, Lever, and Taleo. Generate an ATS-optimized description for a ${title} at ${company} (${roleContext}) that will score highly in automated screening while reading as a natural, compelling human narrative. Your optimization must satisfy dual audiences: for the algorithms, strategically incorporate primary keywords and their common variants that recruiters and ATS systems associate with ${title} positions${industry ? ` in the ${industry} sector` : ""}, include related tools, technologies, methodologies, and domain-specific terminology that expand the keyword profile naturally, align with standard occupational classification frameworks and job taxonomies, use both full terms and common abbreviations/acronyms appropriately (e.g., "Search Engine Optimization (SEO)"), and maintain keyword distribution that achieves high relevance scoring without triggering keyword-stuffing penalties. For the humans, read as a fluid, natural description written by a real professional - not an SEO exercise, demonstrate genuine understanding through contextually appropriate use of terminology (not just keyword insertion), and maintain the authentic voice and specific details that make a description memorable and credible.${skillsUsed ? ` Ensure ${skillsUsed} and related terms are incorporated naturally with evidence of application.` : ""} The ideal output achieves high ATS matching scores while a human recruiter would never guess it was algorithmically optimized. Provide only the description with no visible optimization markers.`,
    },
  ];
};

// Function to generate prompt options for experience achievements
export const getExperienceAchievementsPromptOptions = (
  formData: ExperienceFormData,
  currentText: string,
): PromptOption[] => {
  const { job_title, company_name, start_date } = formData;

  // Return empty array if required fields are missing
  if (!job_title?.trim() || !company_name?.trim() || !start_date?.trim()) {
    return [];
  }

  const hasText = currentText.trim().length > 0;
  const company = company_name.trim();
  const title = job_title.trim();
  const employmentType = formData.employment_type || "full-time";
  const locationType = formData.location_type || "on-site";
  const location = formData.location?.trim();
  const industry = formData.industry?.trim();
  const companySize = formData.company_size?.trim();
  const skillsUsed = formData.skills_used?.trim();
  const description = formData.description?.trim();
  const dateRange = formData.is_current
    ? `since ${start_date}`
    : `from ${start_date} to ${formData.end_date || "present"}`;

  // Build context-rich description
  const roleContext = [
    employmentType,
    locationType,
    location ? `in ${location}` : "",
    industry ? `in the ${industry} industry` : "",
    companySize ? `at a ${companySize.toLowerCase()} company` : "",
  ]
    .filter(Boolean)
    .join(", ");

  const skillsContext = skillsUsed ? ` Key skills used: ${skillsUsed}.` : "";

  const descriptionContext = description
    ? ` Role overview: ${description}`
    : "";

  return [
    {
      title: "Generate achievements",
      prompt: hasText
        ? `You are an executive resume writer and achievement crafting specialist who has helped thousands of professionals articulate their accomplishments in ways that win interviews. Based on this context for a ${title} at ${company}: "${currentText}", generate 5-6 specific, compelling, and quantifiable achievements that demonstrate the full scope and impact of this role. Each achievement must follow the proven formula: [Strong Action Verb] + [Specific Action Taken] + [Quantifiable Result/Impact]. Your achievements should: span different dimensions of impact (financial, operational, team, customer, innovation), be realistic and proportional to this ${roleContext} role - impressive but credible, include specific metrics (percentages, dollar amounts, timeframes, team sizes, growth rates) that make the impact tangible, use dynamic language that conveys ownership, initiative, and leadership, and together tell a complete story of someone who consistently delivered exceptional results.${descriptionContext}${skillsContext} Format each achievement as a standalone, powerful bullet point that could go directly into a resume or LinkedIn profile.`
        : `You are an executive resume writer and achievement crafting specialist who knows that specific, quantified accomplishments are what separate interview-winning resumes from overlooked ones. Generate 5-6 impressive, detailed achievements for a ${title} at ${company} (${roleContext}).${descriptionContext}${skillsContext} Each achievement must follow the proven formula that recruiters and hiring managers respond to: [Powerful Action Verb] + [What Was Done Specifically] + [Measurable Result or Impact]. Your achievements should collectively demonstrate: scope and scale of responsibility (what was entrusted to this person?), specific actions and initiatives taken (what did they actually do beyond the job description?), quantifiable results achieved (what improved, grew, or changed because of their work?), and the unique value they brought to ${company} (what would have been lost or not achieved without them?). Ensure metrics are realistic for ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"}${industry ? ` in ${industry}` : ""}. Include a mix of: revenue/profit impact, efficiency/productivity gains, team/people development, customer/client success, process improvements, and innovation/transformation. Each achievement should be specific enough that it could only belong to this role at this company - avoid generic statements that could apply to anyone.`,
    },
    {
      title: "Revenue impact",
      prompt: hasText
        ? `You are a financial impact specialist and business value consultant who knows how to connect professional activities to bottom-line results. Transform these achievements for a ${title} at ${company} (${roleContext}) to emphasize revenue growth, cost optimization, and financial impact. For each achievement: quantify the financial dimension explicitly - revenue generated, costs reduced, margins improved, ROI delivered, budgets optimized, explain the mechanism - what specific action led to the financial outcome? (This proves causation, not just correlation), provide context that makes the numbers meaningful - percentage improvements, comparisons to previous periods or targets, scale relative to organization size, and use financial language that resonates with executives and business stakeholders. The achievements should paint a picture of someone who understands the business impact of their work and consistently contributes to financial performance. Current text: "${currentText}"`
        : `You are a financial impact specialist and business value consultant who believes that every role, regardless of function, can be connected to financial outcomes. Create 3-4 achievements focused on revenue growth, cost reduction, and financial impact for a ${title} at ${company}${industry ? ` in ${industry}` : ""}. Each achievement should clearly establish: the financial context (budget size, revenue targets, cost challenges, or financial goals), the specific action taken that drove financial impact (initiatives launched, optimizations implemented, strategies deployed, waste eliminated), and the quantified financial result (revenue increase in dollars or percentage, cost savings in absolute or relative terms, ROI percentage, margin improvement, profit contribution). Ensure financial metrics are realistic and proportional for ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"} - a 10% cost reduction means different things at a startup vs. an enterprise. Consider different types of financial impact: top-line growth (new revenue, expanded accounts, new markets), bottom-line improvement (cost reduction, efficiency, vendor optimization), working capital (cash flow improvement, inventory reduction, collections acceleration), and investment returns (project ROI, initiative payback period, resource optimization). Each achievement should demonstrate financial acumen and results-orientation.`,
    },
    {
      title: "Team & leadership",
      prompt: hasText
        ? `You are an organizational development specialist and leadership coach who knows how to articulate people-related achievements in ways that demonstrate exceptional leadership capability. Reformat these achievements for a ${title} at ${company} (${roleContext}) to highlight team leadership, talent development, and organizational impact. Your reframed achievements should demonstrate: team building and scaling - how teams were grown, structured, or transformed, talent development - how individuals were mentored, coached, or developed (with evidence of their growth), culture and engagement - improvements in team morale, retention, collaboration, or performance, hiring and onboarding - recruitment achievements, onboarding improvements, or team composition optimization, and organizational influence - how this person shaped the broader organization beyond their immediate team. Quantify people impact wherever possible: team size and growth rates, retention improvements, promotion rates of team members, engagement survey improvements, diversity metrics, or time-to-hire reductions. Current text: "${currentText}"`
        : `You are an organizational development specialist and leadership coach who understands that people leadership is one of the most valuable and transferable professional capabilities. Generate 3-4 achievements highlighting team leadership, talent development, and organizational impact for a ${title} at ${company}. Scale these achievements appropriately for ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"} - leadership looks different at a 10-person startup versus a 10,000-person enterprise, but it's equally important to articulate. Each achievement should cover a different dimension of people impact: team building & scaling (teams formed, grown, restructured, or transformed - with specific numbers), talent development (mentoring relationships, skill development programs, career progression of direct reports or mentees - with specific outcomes), culture & engagement (initiatives that improved team satisfaction, collaboration, retention, or performance - with measurable results), hiring & talent acquisition (recruitment efforts, hiring volumes, quality improvements, process innovations - with metrics), and organizational leadership (cross-functional initiatives led, committees chaired, culture-building efforts, diversity and inclusion contributions). Use verbs like "mentored," "developed," "built," "cultivated," "championed," "elevated." Each achievement should prove that this person makes teams better, not just completes individual tasks.`,
    },
    {
      title: "Process improvement",
      prompt: hasText
        ? `You are an operations excellence consultant and process optimization specialist who excels at articulating how professionals make organizations run better. Reframe these achievements for a ${title} at ${company} (${roleContext}) to focus on process optimization, efficiency gains, and operational improvements. Your reframed achievements should: identify the specific process or workflow that was improved, describe the analysis and approach taken to identify improvement opportunities, detail the changes implemented (automation, restructuring, standardization, elimination), and quantify the impact - time saved, cost reduced, quality improved, throughput increased, errors eliminated. Use the language of operational excellence: "streamlined," "automated," "optimized," "standardized," "restructured," "eliminated bottlenecks." The achievements should demonstrate systematic thinking and the ability to see and solve operational inefficiencies. Current text: "${currentText}"`
        : `You are an operations excellence consultant and process optimization specialist who knows that the ability to improve how work gets done is one of the most valuable professional capabilities. Create 3-4 achievements focused on process improvements, automation, and efficiency gains for a ${title} at ${company}${skillsUsed ? ` where skills like ${skillsUsed} were applied to drive operational excellence` : ""}. Each achievement should follow a clear structure: identify the problem or inefficiency (what was broken, slow, expensive, or manual?), describe the solution designed and implemented (what was changed, automated, restructured, or optimized?), and quantify the impact (time saved in hours or percentage, cost reduced in dollars or percentage, error rates decreased, throughput increased, capacity expanded). Consider different types of process improvements: automation of manual workflows, standardization of inconsistent processes, elimination of redundant or non-value-adding steps, restructuring of teams or workflows for efficiency, implementation of new tools or systems, and documentation or knowledge management improvements. Metrics should be specific and contextual - saving 5 hours per week is meaningful; "improved efficiency" is not. Each achievement should demonstrate that this professional doesn't just do work - they improve how work is done.`,
    },
    {
      title: "Customer impact",
      prompt: hasText
        ? `You are a customer experience strategist who knows that customer impact achievements are among the most compelling because they connect internal work to external value. Rewrite these achievements for a ${title} at ${company} (${roleContext}) to emphasize customer satisfaction, user growth, client success, and stakeholder impact. Your reframed achievements should: identify the specific customer or user group impacted, describe the improvement in their experience or outcomes, and quantify the impact - satisfaction scores (NPS, CSAT), retention rates, growth metrics, adoption rates, or testimonials/recognition.${industry ? ` For the ${industry} industry, consider what customer impact metrics matter most.` : ""} Frame achievements to show that this person understands that organizational success ultimately depends on serving customers and stakeholders effectively. Current text: "${currentText}"`
        : `You are a customer experience strategist who believes that the most powerful professional achievements are those that demonstrate a clear line from internal work to external value. Generate 3-4 achievements focused on customer satisfaction, client success, and stakeholder impact for a ${title} at ${company}${industry ? ` in the ${industry} industry` : ""}. Each achievement should clearly establish: who the customers or stakeholders were (internal users, external clients, partners, specific user segments), what was done to improve their experience or outcomes (initiatives, improvements, new capabilities, service enhancements), and the quantified impact on these stakeholders (satisfaction scores, NPS improvements, retention rates, adoption metrics, growth in usage, testimonials, repeat business, referrals). Consider different dimensions of customer impact: satisfaction & loyalty (NPS, CSAT, retention, churn reduction), growth & adoption (user acquisition, feature adoption, expansion revenue, usage growth), service & support (response times, resolution rates, support quality improvements), and relationship & trust (client retention, contract renewals, strategic partnership development). Each achievement should demonstrate customer-centric thinking and the ability to translate organizational capabilities into stakeholder value. Metrics should be specific and meaningful within the context of ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"}.`,
    },
    {
      title: "Innovation focus",
      prompt: hasText
        ? `You are an innovation strategist and transformation consultant who helps professionals articulate their role in creating change and driving progress. Transform these achievements for a ${title} at ${company} (${roleContext}) to highlight innovation, new initiatives, and transformative contributions. Your reframed achievements should: identify what was created, launched, or transformed that didn't exist before, describe the innovative approach or novel solution applied, and quantify the impact - adoption rates, time to market, competitive advantage gained, revenue from new offerings, or efficiency breakthroughs. Use language of innovation: "pioneered," "created," "launched," "transformed," "reimagined," "invented," "disrupted." The achievements should demonstrate that this person doesn't just maintain the status quo - they create new value and move organizations forward. Current text: "${currentText}"`
        : `You are an innovation strategist and transformation consultant who knows that the most impressive achievements are those that show someone creating something new or fundamentally improving something existing. Create 3-4 achievements showcasing innovation, new initiatives, and transformative impact for a ${title} at ${company}${industry ? ` in ${industry}` : ""}. Each achievement should tell a story of creation or transformation: what was the situation before? (the gap, the outdated approach, the missed opportunity), what was created, launched, or transformed? (the new product, process, initiative, system, or approach), what was innovative about it? (what made this different from business as usual or from what competitors were doing?), and what was the impact? (adoption, growth, efficiency, competitive advantage, revenue, recognition). Consider different types of innovation: product/service innovation (new offerings, features, or capabilities), process innovation (new ways of working that created step-change improvements), business model innovation (new revenue streams, channels, or value propositions), technology innovation (novel applications of technology to solve problems), and organizational innovation (new structures, practices, or cultural initiatives). Metrics should reflect the scale of innovation - a 30% improvement through optimization is good; creating an entirely new revenue stream is different. Each achievement should position this person as someone who drives change, not just manages the present.`,
    },
    {
      title: "Skill-driven results",
      prompt: hasText
        ? `You are a competency-based assessment specialist who knows that the best way to demonstrate skills is through the results they produce. Rewrite these achievements for a ${title} at ${company} to explicitly connect specific skills to measurable outcomes. For each achievement: name the skill or competency applied (technical skill, soft skill, domain expertise), describe how it was applied to a specific situation or challenge, and quantify the result achieved through that application.${skillsUsed ? ` With skills including ${skillsUsed}, show how these capabilities directly drove business or organizational results.` : ""} This approach proves capability through evidence rather than claims. Current text: "${currentText}"`
        : `You are a competency-based assessment specialist who believes that skills should be demonstrated through their impact, not just listed on a resume. Generate 3-4 achievements that explicitly demonstrate how applying ${skillsUsed || "key professional competencies"} as a ${title} at ${company} drove specific, measurable results. Each achievement should follow a clear chain of causation: the skill or competency applied (be specific - not "technical skills" but "Python and SQL for data analysis"), how it was applied to a real situation (the context, challenge, or opportunity), and the measurable result produced (the outcome that would not have occurred without this skill application). This approach transforms claims of capability into evidence of impact. Consider different types of skill application: technical skills driving efficiency, quality, or innovation, analytical skills driving insights, decisions, or optimizations, leadership skills driving team performance, engagement, or development, communication skills driving alignment, buy-in, or stakeholder satisfaction, and domain expertise driving industry-specific outcomes or competitive advantage. Each achievement should make a clear case that this person's capabilities translate directly into organizational value.`,
    },
    {
      title: "Company scale impact",
      prompt: hasText
        ? `You are a startup-to-enterprise career strategist who understands that achievements must be framed differently depending on organizational context. Adjust these achievements for a ${title} at ${company} to reflect the scale and scope appropriate for ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"}${industry ? ` in ${industry}` : ""}. For each achievement: calibrate metrics to be impressive for this context (what's remarkable at a startup differs from what's remarkable at a Fortune 500), frame the scope of responsibility appropriately (wearing multiple hats vs. deep specialization), and highlight context-specific challenges and successes. Current text: "${currentText}"`
        : `You are a startup-to-enterprise career strategist who knows that the same achievement can look either underwhelming or incredible depending on how it's framed for the organizational context. Create 3-4 achievements scaled appropriately for ${companySize ? `a ${companySize.toLowerCase()} company` : "this organization"}${industry ? ` in ${industry}` : ""} for a ${title} role. Understand the context: if this is a small company/startup, achievements should emphasize breadth, scrappiness, resourcefulness, speed, and outsized impact relative to resources, if mid-size, achievements should balance breadth and depth, showing both hands-on contribution and process/system building, and if enterprise, achievements should emphasize scale, complexity management, stakeholder navigation, and impact on large systems/organizations. For each achievement: calibrate metrics to what's impressive for this organization size (leading a $100K project at a 10-person startup is different from a $100K project at a multinational), frame responsibilities in context-appropriate terms (at a startup, being "the person who built X from scratch" matters; at an enterprise, "managed a $10M P&L" matters), and highlight challenges specific to this organizational scale (resource constraints at small companies, complexity and politics at large ones). The achievements should make sense and impress within their specific context.`,
    },
    {
      title: "STAR format",
      prompt: hasText
        ? `You are a behavioral interviewing coach and structured achievement specialist who excels at the STAR (Situation, Task, Action, Result) format. Convert these achievements for a ${title} at ${company} into detailed STAR-format accomplishments. For each achievement, provide: Situation - the context, environment, and circumstances (what was happening? what was the challenge or opportunity?), Task - the specific responsibility, goal, or objective (what needed to be accomplished? what was your role?), Action - the specific steps taken, skills applied, and decisions made (what did you actually do? how did you approach it?), and Result - the quantifiable outcome, impact, and lessons learned (what changed? what was achieved? what did you learn?). Context: ${roleContext}${descriptionContext}. Current text: "${currentText}"`
        : `You are a behavioral interviewing coach and structured achievement specialist who knows that the STAR format is the gold standard for articulating accomplishments in interviews, performance reviews, and executive resumes. Generate 3-4 detailed STAR-format achievements for a ${title} at ${company} (${roleContext}).${descriptionContext} For each achievement, provide a complete STAR narrative: **Situation** - Set the scene with rich context. What was the organizational environment? What challenges or opportunities existed? What was the business or team context that made this situation significant? Be specific about the stakes, constraints, and initial conditions, **Task** - Define your specific responsibility or objective. What were you tasked with accomplishing? What goals, targets, or expectations were set? What was your role in the situation (leader, contributor, influencer)? Clarify what success would look like, **Action** - Detail your specific actions with precision. What did you personally do? What steps did you take? What skills, methodologies, or approaches did you apply? What obstacles did you navigate? What decisions did you make? This is where you demonstrate your capability - be thorough and specific, and **Result** - Quantify the outcome comprehensively. What changed as a result of your actions? Include metrics (numbers, percentages, dollar amounts), qualitative impacts (recognition, adoption, satisfaction), and any lessons learned or capabilities developed. The result should clearly connect back to the situation and task, showing that you delivered meaningful value. Each STAR achievement should be detailed enough to serve as a complete story that would impress in an interview setting. Use professional formatting to make each component clear and distinct.`,
    },
  ];
};
